PILOTCTL ?= ./pilotctl.sh

.PHONY: install update build start stop restart status smoke logs

install:
	$(PILOTCTL) install

update:
	$(PILOTCTL) update

build:
	$(PILOTCTL) build

start:
	$(PILOTCTL) start

stop:
	$(PILOTCTL) stop

restart:
	$(PILOTCTL) restart

status:
	$(PILOTCTL) status

smoke:
	$(PILOTCTL) smoke

logs:
	$(PILOTCTL) logs

