/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/android-device-management-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/devices/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-register an Android device using an operator-issued pairing code.
         * @description The operator generates a pairing code through the admin
         *     console (out of scope of this endpoint) and shares it
         *     with the device. The device then calls this route to
         *     register itself: the backend creates a new `AndroidDevice`
         *     row in `status = pending` (until an operator assigns role
         *     and binding) and returns the persistent device token used
         *     for subsequent device-side calls.
         */
        post: operations["androidDeviceRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current state of the calling device.
         * @description Authenticated device-side route. The backend resolves the
         *     caller from the bearer device token issued at registration
         *     and returns the device row including current role, binding
         *     and status. Used by the Android client to discover its
         *     assignment after an operator approves it.
         */
        get: operations["androidDeviceSelfGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report device liveness and runtime state.
         * @description Device-side keep-alive. The backend stamps `lastSeenAt`
         *     and records the latest heartbeat snapshot (OS version,
         *     battery, network class) — used by operators to monitor
         *     fleet health. Devices in `retired` status are rejected
         *     with `409`.
         */
        post: operations["androidDeviceHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Android devices in the fleet. */
        get: operations["androidDeviceAdminList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        /** Get a single device record by id. */
        get: operations["androidDeviceAdminGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices/{deviceId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign role and binding to a device.
         * @description Operator-initiated transition `pending → active`. The body
         *     carries the role (`registrar` or `vehicleVerifier`) and the
         *     binding ref. The backend rejects with `422` if the role
         *     and binding type are inconsistent — e.g. a `registrar`
         *     cannot bind to `vehicle`, and a `vehicleVerifier` cannot
         *     bind to `receptionPoint`/`workstation`. Re-assignment of an
         *     already-active device is allowed (it updates the binding);
         *     retired devices are rejected with `409`.
         */
        post: operations["androidDeviceAdminAssign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices/{deviceId}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retire a device (terminal lifecycle transition).
         * @description Operator-initiated transition to `retired`. The device
         *     token is invalidated and further `/devices/me` or
         *     `/devices/{deviceId}/heartbeat` calls from that device
         *     get `401` (token revoked) or `409` (retired). Already-
         *     retired devices are rejected with
         *     `409 ANDROID_DEVICE_NOT_RETIREABLE`.
         */
        post: operations["androidDeviceAdminRetire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /**
         * @description Lifecycle of an Android device record.
         *     * `pending` — registered, awaiting operator assignment;
         *     * `active` — role + binding assigned, may call its scoped
         *       downstream APIs;
         *     * `retired` — terminal; device token revoked, no further
         *       self-state or heartbeat calls accepted.
         * @enum {string}
         */
        AndroidDeviceStatus: "pending" | "active" | "retired";
        /**
         * @description Functional role assigned to a device.
         *     * `registrar` — enrollment-side, bound to a reception
         *       point or workstation;
         *     * `vehicleVerifier` — verification-side, bound to a vehicle.
         * @enum {string}
         */
        AndroidDeviceRole: "registrar" | "vehicleVerifier";
        /**
         * @description Anchor type the device is bound to. The valid set depends
         *     on the role: a `registrar` accepts `receptionPoint` or
         *     `workstation`; a `vehicleVerifier` accepts `vehicle`.
         * @enum {string}
         */
        AndroidDeviceBindingType: "receptionPoint" | "workstation" | "vehicle";
        /**
         * @description Binding of an active device to an anchor entity owned by
         *     another service (`reference-data-service` for reception
         *     points and workstations, `vehicle-service` for vehicles).
         */
        AndroidDeviceBinding: {
            type: components["schemas"]["AndroidDeviceBindingType"];
            /**
             * Format: uuid
             * @description Opaque reference to the anchor row in the owning service.
             */
            anchorId: string;
        };
        /**
         * @description Backend-owned canonical name of an Android device surface.
         *     The Android client maps each capability to its own
         *     Compose/View screen — backend MUST NOT reference framework
         *     identifiers (Activity / Fragment / Composable class names)
         *     and MUST NOT carry user-facing labels.
         *
         *     Current set:
         *     * `enrollmentCapture` — face capture screen used by
         *       `registrar` devices during enrollment launches;
         *     * `verificationCapture` — pre-exam face verification
         *       screen used by `vehicleVerifier` devices;
         *     * `passiveFaceCheck` — in-exam passive face check screen
         *       on `vehicleVerifier`;
         *     * `devicePairing` — pairing / first-run setup screen;
         *     * `diagnostics` — operator-visible diagnostics screen;
         *     * `settings` — runtime settings screen.
         *
         *     The enum is intentionally additive: future capabilities
         *     land as backward-compatible additions inside this v1
         *     contract. Mobile clients MUST gracefully ignore unknown
         *     capability names in `disabledCapabilities` so a forward-
         *     rolled backend does not break older clients.
         * @enum {string}
         */
        AndroidDeviceCapability: "enrollmentCapture" | "verificationCapture" | "passiveFaceCheck" | "devicePairing" | "diagnostics" | "settings";
        /**
         * @description Per-device capability policy. Lists **disabled**
         *     capabilities — positive list semantics ("everything not in
         *     the disabled set is allowed") so a default-empty policy
         *     means "device has full access to all capabilities its
         *     role permits". `policyVersion` is a monotonic integer
         *     assigned by the backend; it increments on every successful
         *     policy update so the device can detect re-sync need
         *     through `GET /devices/me`. `policyReason` is an
         *     operator-supplied audit string describing why specific
         *     capabilities are disabled; MUST NOT contain candidate PII.
         */
        AndroidDeviceCapabilityPolicy: {
            /** @description Monotonic per-device version stamp. Incremented by the backend on every successful policy update. */
            policyVersion: number;
            /**
             * @description Set of capabilities currently disabled for this device.
             *     Empty array means the device has full role-default access.
             *     Unknown values on the client side MUST be ignored
             *     (forward compatibility within v1).
             */
            disabledCapabilities: components["schemas"]["AndroidDeviceCapability"][];
            /**
             * @description Operator-supplied audit note explaining why these
             *     capabilities are disabled. Forwarded to the device so
             *     the client can display an operator-friendly tooltip;
             *     MUST NOT contain candidate PII.
             */
            policyReason?: string;
            /**
             * Format: date-time
             * @description Server timestamp at which the policy was last updated. Set by the backend.
             */
            updatedAt?: string;
        };
        /**
         * @description Device platform/runtime metadata supplied at registration
         *     and refreshed via heartbeats. Pure-metadata; no PII.
         */
        AndroidDevicePlatform: {
            manufacturer: string;
            model: string;
            osVersion: string;
            appVersion: string;
            /**
             * @description Opaque, vendor-supplied hardware identifier (e.g. ANDROID_ID
             *     scoped to the app installation). MUST NOT include IMEI,
             *     serial number or any reversible PII; the field is treated
             *     as an opaque correlator for fleet operators.
             */
            hardwareId?: string;
        };
        /**
         * @description Self-registration request. The pairing code is operator-
         *     issued out-of-band; the device supplies its platform info
         *     and an optional push-notification channel token for future
         *     command transport.
         */
        AndroidDeviceRegistration: {
            /**
             * @description Opaque single-use pairing code issued by the operator
             *     through the admin console. Validated server-side and
             *     consumed on successful registration.
             */
            pairingCode: string;
            platform: components["schemas"]["AndroidDevicePlatform"];
            /**
             * @description Optional FCM/HMS push channel token for server-to-device
             *     command delivery. Treated as opaque; rotation handled by
             *     the device on subsequent heartbeats once a heartbeat
             *     schema extension lands.
             */
            pushChannelToken?: string;
        };
        AndroidDeviceRegistrationResult: {
            device: components["schemas"]["AndroidDevice"];
            /**
             * @description Persistent bearer token to authenticate further device-
             *     side calls. Revoked on `retire` or on operator-initiated
             *     re-pair. MUST NOT be logged in plaintext outside the
             *     secure device keystore.
             */
            deviceToken: string;
        };
        /**
         * @description Operator request to move a device from `pending` to
         *     `active` (or to update an existing active device's binding
         *     and/or capability policy).
         *     Server validates role/binding-type consistency:
         *     `registrar` MUST bind to `receptionPoint`/`workstation`;
         *     `vehicleVerifier` MUST bind to `vehicle`. Inconsistent
         *     combinations return `422 INVALID_BINDING_FOR_ROLE`.
         */
        AndroidDeviceAssignment: {
            role: components["schemas"]["AndroidDeviceRole"];
            binding: components["schemas"]["AndroidDeviceBinding"];
            /**
             * @description Optional capability policy update. When supplied, the
             *     backend replaces the device's current policy with this
             *     value and bumps `policyVersion` on the new state.
             *     Omitting `policy` keeps the existing policy intact —
             *     so operators can re-bind without re-stating capability
             *     decisions. On the very first assignment (transition
             *     `pending → active`) omitting `policy` results in an
             *     empty `disabledCapabilities` and `policyVersion = 1`
             *     (full role-default access).
             */
            policy?: components["schemas"]["AndroidDeviceCapabilityPolicyUpdate"];
            /** @description Operator-side audit note; not forwarded to the device. */
            notes?: string;
        };
        /**
         * @description Operator-side write shape for capability policy. The server
         *     owns `policyVersion` and `updatedAt` and ignores them if
         *     sent by the client; only `disabledCapabilities` and
         *     `policyReason` are accepted as input.
         */
        AndroidDeviceCapabilityPolicyUpdate: {
            disabledCapabilities: components["schemas"]["AndroidDeviceCapability"][];
            policyReason?: string;
        };
        AndroidDeviceRetireRequest: {
            /** @description Operator-side audit note for the retirement. */
            reason?: string;
        };
        /**
         * @description Single device keep-alive snapshot. The backend stamps
         *     `lastSeenAt` and merges the latest values into the
         *     `AndroidDevice` row. High-frequency endpoint — clients
         *     should send heartbeats at the cadence agreed in the
         *     fleet ops document (future).
         */
        AndroidDeviceHeartbeat: {
            /**
             * Format: date-time
             * @description Device-local timestamp at capture.
             */
            capturedAt: string;
            /**
             * @description Device-reported availability. `degraded` signals the
             *     device is reachable but in a constrained state (low
             *     battery, poor connectivity, background restrictions
             *     preventing capture).
             * @enum {string}
             */
            status: "online" | "offline" | "degraded";
            /** @description Battery charge fraction (0.0..1.0). */
            batteryLevel?: number;
            batteryCharging?: boolean;
            /** @enum {string} */
            networkType?: "wifi" | "cellular" | "ethernet" | "none" | "other";
            /** @description Reported OS version; if it differs from the stored value, the backend may refresh `platform.osVersion`. */
            osVersion?: string;
            appVersion?: string;
        };
        AndroidDeviceHeartbeatAccepted: {
            /** Format: uuid */
            deviceId: string;
            /** Format: date-time */
            acceptedAt: string;
            /**
             * Format: date-time
             * @description Earliest server-recommended timestamp for the next
             *     heartbeat. Devices should not heartbeat more
             *     frequently; the backend MAY rate-limit further calls.
             */
            nextHeartbeatAfter: string;
        };
        /**
         * @description Canonical device row. Carries identity, lifecycle status,
         *     optional role/binding (only after operator assignment),
         *     optional capability policy (set during/after assignment),
         *     platform metadata and last-seen timestamps. No candidate
         *     PII, no biometric data.
         */
        AndroidDevice: {
            /** Format: uuid */
            deviceId: string;
            status: components["schemas"]["AndroidDeviceStatus"];
            role?: components["schemas"]["AndroidDeviceRole"];
            binding?: components["schemas"]["AndroidDeviceBinding"];
            /**
             * @description Capability policy currently in effect for this device.
             *     Present once the device has been assigned (`status =
             *     active`) — `pending` devices have no policy yet.
             *     Synced to the Android client through
             *     `GET /devices/me`; the device compares
             *     `policy.policyVersion` against its locally cached
             *     value to decide when to apply changes.
             */
            policy?: components["schemas"]["AndroidDeviceCapabilityPolicy"];
            platform: components["schemas"]["AndroidDevicePlatform"];
            /** Format: date-time */
            registeredAt: string;
            /**
             * Format: date-time
             * @description Set on the transition `pending → active`.
             */
            assignedAt?: string;
            /**
             * Format: date-time
             * @description Set on the transition `* → retired`.
             */
            retiredAt?: string;
            /**
             * Format: date-time
             * @description Last successful heartbeat or self-state call.
             */
            lastSeenAt?: string;
            /**
             * @description Last received heartbeat snapshot — operator-facing
             *     convenience field. Kept inline so the admin UI does
             *     not need a separate fetch for status pills.
             */
            lastHeartbeat?: {
                /** Format: date-time */
                capturedAt?: string;
                /** @enum {string} */
                status?: "online" | "offline" | "degraded";
                batteryLevel?: number;
                batteryCharging?: boolean;
                /** @enum {string} */
                networkType?: "wifi" | "cellular" | "ethernet" | "none" | "other";
            };
        };
        AndroidDevicesPage: {
            items: components["schemas"]["AndroidDevice"][];
            nextPageToken?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Conflicting state, including `IDEMPOTENCY_CONFLICT`,
         *     `ANDROID_DEVICE_NOT_RETIREABLE`,
         *     `ANDROID_DEVICE_HEARTBEAT_REJECTED`.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        DeviceIdPath: string;
        PageSize: number;
        PageToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    androidDeviceRegister: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AndroidDeviceRegistration"];
            };
        };
        responses: {
            /** @description Device registered. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDeviceRegistrationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    androidDeviceSelfGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device record. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDevice"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    androidDeviceHeartbeat: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AndroidDeviceHeartbeat"];
            };
        };
        responses: {
            /** @description Heartbeat accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDeviceHeartbeatAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    androidDeviceAdminList: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle status. */
                status?: components["schemas"]["AndroidDeviceStatus"];
                /** @description Filter by assigned role. */
                role?: components["schemas"]["AndroidDeviceRole"];
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDevicesPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    androidDeviceAdminGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device record. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDevice"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    androidDeviceAdminAssign: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AndroidDeviceAssignment"];
            };
        };
        responses: {
            /** @description Device after assignment. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDevice"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    androidDeviceAdminRetire: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deviceId: components["parameters"]["DeviceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AndroidDeviceRetireRequest"];
            };
        };
        responses: {
            /** @description Device after retirement. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AndroidDevice"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
