/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/audit-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search audit events with cursor pagination. */
        get: operations["auditEventsList"];
        put?: never;
        /**
         * Append a critical audit event.
         * @description Append-only write. The server computes the payload hash and
         *     links the event into the hash chain. Mutating command —
         *     requires `Idempotency-Key`.
         */
        post: operations["auditEventAppend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a hash-chain checkpoint. */
        post: operations["auditCheckpointCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify the audit hash chain.
         * @description Recomputes the chain and returns a verification report. A
         *     broken chain is reported with `status = failed` and also emits
         *     `autodrome.audit.verification_failed.v1`.
         */
        post: operations["auditVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an audit export. */
        post: operations["auditExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
        };
        AuditEventAppend: {
            actor: components["schemas"]["ActorContext"];
            /** @description Canonical action key, e.g. `identity.token_revoked`. */
            action: string;
            /** @description Subject reference the action applied to (id or key). */
            subject: string;
            /** Format: date-time */
            occurredAt: string;
            /** @description Optional structured detail; the server stores its hash. */
            payload?: {
                [key: string]: unknown;
            };
        };
        AuditEvent: {
            /** Format: uuid */
            eventId: string;
            actor: components["schemas"]["ActorContext"];
            action: string;
            subject: string;
            /** Format: date-time */
            occurredAt: string;
            /** @description Hex SHA-256 of the canonicalized payload. */
            payloadHash: string;
            /**
             * Format: int64
             * @description Monotonic append sequence within the chain.
             */
            sequence: number;
            /** Format: uuid */
            correlationId?: string;
            /** Format: date-time */
            recordedAt: string;
        };
        AuditEventsPage: {
            items: components["schemas"]["AuditEvent"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
        AuditChainBlock: {
            /** Format: uuid */
            blockId: string;
            previousHash?: string;
            eventsHash: string;
            blockHash: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditCheckpoint: {
            /** Format: uuid */
            checkpointId: string;
            /** Format: uuid */
            blockId: string;
            checkpointHash: string;
            /** Format: uuid */
            previousCheckpointId?: string;
            checkedBlocksCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        AuditVerificationReport: {
            /** Format: uuid */
            runId: string;
            /** @enum {string} */
            status: "passed" | "failed";
            checkedBlocks: number;
            /** Format: uuid */
            firstErrorBlockId?: string;
            firstError?: string;
            /** Format: date-time */
            ranAt: string;
        };
        AuditExportRequest: {
            /** @enum {string} */
            format: "jsonl" | "csv";
            /** Format: date-time */
            occurredAtFrom?: string;
            /** Format: date-time */
            occurredAtTo?: string;
        };
        AuditExport: {
            /** Format: uuid */
            exportId: string;
            /** @enum {string} */
            format: "jsonl" | "csv";
            eventCount: number;
            /** Format: date-time */
            occurredAtFrom?: string;
            /** Format: date-time */
            occurredAtTo?: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Conflicting state. Common codes: `IDEMPOTENCY_CONFLICT`,
         *     `AUDIT_VERIFICATION_FAILED`, `AUDIT_APPEND_ONLY_VIOLATION`.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auditEventsList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                action?: string;
                actorId?: string;
                occurredAtFrom?: string;
                occurredAtTo?: string;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    auditEventAppend: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditEventAppend"];
            };
        };
        responses: {
            /** @description Audit event appended. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    auditCheckpointCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkpoint created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditCheckpoint"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    auditVerify: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification report. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerificationReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    auditExport: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditExportRequest"];
            };
        };
        responses: {
            /** @description Export created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditExport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
