/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/autodrome-geometry-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List geometry objects. */
        get: operations["geometryList"];
        put?: never;
        /** Create / import a geometry object. */
        post: operations["geometryCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geometry/{geometryId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                geometryId: components["parameters"]["GeometryIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a geometry snapshot version. */
        post: operations["geometryPublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geometry/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionIdPath"];
            };
            cookie?: never;
        };
        /** Get a published geometry snapshot. */
        get: operations["geometrySnapshotGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @enum {string} */
        GeometryType: "line" | "notificationLine" | "zone" | "obstaclePattern";
        GeometryObjectCreate: {
            type: components["schemas"]["GeometryType"];
            name?: string;
            srid: number;
            /** @description Neutral JSON coordinate payload (GeoJSON-like); no PostGIS lock-in. */
            coordinates: {
                [key: string]: unknown;
            };
            properties?: {
                [key: string]: unknown;
            };
        };
        GeometryObject: {
            /** Format: uuid */
            geometryId: string;
            type: components["schemas"]["GeometryType"];
            name?: string;
            srid: number;
            coordinates: {
                [key: string]: unknown;
            };
            properties?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        GeometryObjectsPage: {
            items: components["schemas"]["GeometryObject"][];
            nextPageToken?: string;
        };
        GeometryVersion: {
            /** Format: uuid */
            versionId: string;
            version: number;
            checksum: string;
            objectCount: number;
            /** Format: date-time */
            publishedAt: string;
        };
        GeometrySnapshot: {
            /** Format: uuid */
            versionId: string;
            version: number;
            checksum: string;
            objects: components["schemas"]["GeometryObject"][];
            /** Format: date-time */
            publishedAt: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflict. IDEMPOTENCY_CONFLICT, GEOMETRY_NOTHING_TO_PUBLISH. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        GeometryIdPath: string;
        VersionIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    geometryList: {
        parameters: {
            query?: {
                type?: components["schemas"]["GeometryType"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Geometry objects. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryObjectsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    geometryCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeometryObjectCreate"];
            };
        };
        responses: {
            /** @description Geometry object created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryObject"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    geometryPublish: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                geometryId: components["parameters"]["GeometryIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version published. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryVersion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    geometrySnapshotGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                versionId: components["parameters"]["VersionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Geometry snapshot. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometrySnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
