/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/biometry-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/biometry/enrollment-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enrollment channels and their availability.
         * @description Returns the matrix of registrar devices and camera stations the
         *     operator can pick for an enrollment launch. Availability is
         *     derived from device/station health and current load.
         */
        get: operations["biometryEnrollmentChannelsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-launches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launch enrollment for a candidate on a chosen channel.
         * @description Operator-initiated. Creates an enrollment launch row in `ready`
         *     state and dispatches the capture command to the chosen channel
         *     (`androidRegistrar` or `webCameraStation`). The underlying
         *     enrollment session is created by the backend on the channel's
         *     first acknowledgement (`state=command_sent`). The launch does NOT
         *     carry candidate PII — only `candidateRef.candidateId` and an
         *     operator-supplied `maskedCandidateFacts.displayName` for the
         *     device screen.
         */
        post: operations["biometryEnrollmentLaunch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-launches/{launchId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launchId: components["parameters"]["LaunchIdPath"];
            };
            cookie?: never;
        };
        /** Get current state of an enrollment launch. */
        get: operations["biometryEnrollmentLaunchGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-launches/{launchId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launchId: components["parameters"]["LaunchIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an enrollment launch.
         * @description Operator-initiated cancellation. Allowed in non-terminal states
         *     (`ready`, `command_sent`, `capturing`, `quality_failed`,
         *     `finalizing`); rejected with `409 ENROLLMENT_LAUNCH_NOT_CANCELLABLE`
         *     from a terminal state (`succeeded`, `failed`, `expired`,
         *     `cancelled`).
         */
        post: operations["biometryEnrollmentLaunchCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-launches/{launchId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launchId: components["parameters"]["LaunchIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry an enrollment launch that failed quality check.
         * @description Operator-initiated retry. Allowed only from `quality_failed`;
         *     rejected with `409 ENROLLMENT_LAUNCH_NOT_RETRIABLE` from any
         *     other state. Returns the same `launchId` with `state` reset to
         *     `command_sent` and `retryCount` incremented.
         */
        post: operations["biometryEnrollmentLaunchRetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an enrollment session for a candidate. */
        post: operations["biometryEnrollmentSessionStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-sessions/{sessionId}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a frame to an enrollment session.
         * @description Frame bytes are not transmitted via this API; the request references the
         *     uploaded frame by `frameRef`. Upload mechanics are out of scope of this spec.
         */
        post: operations["biometryEnrollmentFrameUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/enrollment-sessions/{sessionId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize an enrollment session and create a face template. */
        post: operations["biometryEnrollmentFinalize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/verification-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a verification session before exam start. */
        post: operations["biometryVerificationSessionStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/verification-sessions/{sessionId}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a frame to a verification session. */
        post: operations["biometryVerificationFrameUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/verification-sessions/{sessionId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize a verification session and obtain decision. */
        post: operations["biometryVerificationFinalize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/biometry/passive-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a passive face check during an exam. */
        post: operations["biometryPassiveCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @description Reference to candidate-service entity. Id-only. */
        CandidateRef: {
            /** Format: uuid */
            candidateId: string;
        };
        /** @description Reference to exam-service entity. Id-only. */
        ExamRef: {
            /** Format: uuid */
            examId: string;
        };
        /**
         * @description Reference to a media segment or capture in media-archive-service.
         *     Mirrors `MediaRefDto` from media-archive-service.md.
         */
        MediaRef: {
            /** Format: uuid */
            recordingId: string;
            /** Format: uuid */
            segmentId?: string;
            /** Format: date-time */
            timestamp?: string;
            source: string;
        };
        /** @enum {string} */
        EnrollmentSessionStatus: "active" | "finalized" | "failed" | "expired";
        EnrollmentSessionStart: {
            candidateRef: components["schemas"]["CandidateRef"];
            /** Format: uuid */
            deviceId?: string;
        };
        EnrollmentSession: {
            /** Format: uuid */
            sessionId: string;
            candidateRef: components["schemas"]["CandidateRef"];
            status: components["schemas"]["EnrollmentSessionStatus"];
            challengeSequence: ("center" | "left" | "right" | "up" | "down")[];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt?: string;
        };
        FrameUpload: {
            /** @enum {string} */
            step: "center" | "left" | "right" | "up" | "down";
            /** @description Opaque reference to the uploaded frame; upload mechanics out of scope. */
            frameRef: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: date-time */
            capturedAt: string;
            quality?: number;
        };
        FrameAccepted: {
            /** Format: uuid */
            sessionId: string;
            step: string;
            /** Format: date-time */
            acceptedAt: string;
            quality?: number;
        };
        BiometryModelRef: {
            modelId: string;
            modelVersion: string;
        };
        FaceTemplate: {
            /** Format: uuid */
            templateId: string;
            candidateRef: components["schemas"]["CandidateRef"];
            modelRef: components["schemas"]["BiometryModelRef"];
            embeddingDim: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        VerificationSessionStatus: "active" | "finalized" | "failed" | "expired";
        VerificationSessionStart: {
            candidateRef: components["schemas"]["CandidateRef"];
            examRef: components["schemas"]["ExamRef"];
            /** Format: uuid */
            deviceId?: string;
        };
        VerificationSession: {
            /** Format: uuid */
            sessionId: string;
            candidateRef: components["schemas"]["CandidateRef"];
            examRef: components["schemas"]["ExamRef"];
            status: components["schemas"]["VerificationSessionStatus"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        VerificationDecisionOutcome: "passed" | "failed" | "degraded";
        VerificationDecision: {
            /** Format: uuid */
            sessionId: string;
            candidateRef: components["schemas"]["CandidateRef"];
            examRef: components["schemas"]["ExamRef"];
            decision: components["schemas"]["VerificationDecisionOutcome"];
            score: number;
            threshold: number;
            reason?: string;
            modelRef?: components["schemas"]["BiometryModelRef"];
            /** Format: date-time */
            decidedAt: string;
        };
        /** @enum {string} */
        PassiveFaceCheckDecision: "match" | "noMatch" | "lowQuality" | "suspectedSpoof" | "degraded";
        PassiveFaceCheckRequest: {
            examRef: components["schemas"]["ExamRef"];
            candidateRef: components["schemas"]["CandidateRef"];
            /** Format: date-time */
            capturedAt: string;
            mediaRef?: components["schemas"]["MediaRef"];
        };
        PassiveFaceCheck: {
            /** Format: uuid */
            passiveCheckId: string;
            examRef: components["schemas"]["ExamRef"];
            candidateRef: components["schemas"]["CandidateRef"];
            /** Format: date-time */
            capturedAt: string;
            decision: components["schemas"]["PassiveFaceCheckDecision"];
            score?: number;
            modelRef?: components["schemas"]["BiometryModelRef"];
            mediaRef?: components["schemas"]["MediaRef"];
        };
        /**
         * @description Channel through which an enrollment is performed.
         *     `androidRegistrar` — capture happens on a dedicated Android
         *     device operated by the registrar; `webCameraStation` — capture
         *     happens on a Web camera kiosk.
         * @enum {string}
         */
        EnrollmentChannelKind: "androidRegistrar" | "webCameraStation";
        /**
         * @description Lifecycle of an enrollment launch.
         *     * `ready` — launch row created, awaiting dispatch to the chosen
         *       channel.
         *     * `command_sent` — command pushed to the device/station; the
         *       underlying enrollment session has been created.
         *     * `capturing` — device/station acknowledged the command and
         *       capture is in progress.
         *     * `quality_failed` — capture finished but quality below
         *       threshold. Non-terminal — retry possible via
         *       `/enrollment-launches/{launchId}/retry`.
         *     * `finalizing` — capture acceptable; face template generation in
         *       progress.
         *     * `succeeded` — terminal. Face template ready;
         *       `templateId` populated.
         *     * `failed` — terminal, non-recoverable error.
         *     * `expired` — terminal, TTL elapsed without progression.
         *     * `cancelled` — terminal, operator cancelled the launch via
         *       `/enrollment-launches/{launchId}/cancel`.
         * @enum {string}
         */
        EnrollmentLaunchState: "ready" | "command_sent" | "capturing" | "quality_failed" | "finalizing" | "succeeded" | "failed" | "expired" | "cancelled";
        /** @description Target an Android registrar device for capture. */
        AndroidRegistrarTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "androidRegistrar";
            /**
             * Format: uuid
             * @description Registrar device identifier (registered in equipment registry).
             */
            deviceId: string;
        };
        /** @description Target a Web camera station for capture. */
        WebCameraStationTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "webCameraStation";
            /**
             * Format: uuid
             * @description Camera-station identifier (registered in equipment registry).
             */
            stationId: string;
        };
        /**
         * @description Discriminated union of supported capture channels.
         *     Discriminator: `kind`.
         */
        EnrollmentLaunchTarget: components["schemas"]["AndroidRegistrarTarget"] | components["schemas"]["WebCameraStationTarget"];
        /**
         * @description Minimal candidate facts safe to forward to a registrar device or
         *     camera station. The display name MUST be operator-supplied (or
         *     derived server-side from candidate-service) in a masked form —
         *     e.g. "Иван Б." — and MUST NOT carry the full personal name, date
         *     of birth, passport / id number, or any other regulated PII. Full
         *     PII remains in `candidate-service` and is visible only on the
         *     operator Web UI.
         */
        MaskedCandidateFacts: {
            displayName: string;
        };
        /**
         * @description Operator-supplied request to launch a new enrollment. The
         *     registrar device or camera station identified by `target` will
         *     receive the capture command together with the launch metadata.
         */
        EnrollmentLaunchRequest: {
            candidateRef: components["schemas"]["CandidateRef"];
            target: components["schemas"]["EnrollmentLaunchTarget"];
            maskedCandidateFacts?: components["schemas"]["MaskedCandidateFacts"];
            /** @description Operator-side note attached to the launch row (not forwarded to the device). */
            notes?: string;
        };
        /**
         * @description Reason carried with `state=failed` / `state=quality_failed`.
         *     Mirrors the canonical error code/message shape but lives inside
         *     the launch row so consumers can render it without a separate
         *     fetch.
         */
        EnrollmentLaunchError: {
            code: string;
            message: string;
        };
        EnrollmentLaunch: {
            /** Format: uuid */
            launchId: string;
            candidateRef: components["schemas"]["CandidateRef"];
            target: components["schemas"]["EnrollmentLaunchTarget"];
            maskedCandidateFacts?: components["schemas"]["MaskedCandidateFacts"];
            state: components["schemas"]["EnrollmentLaunchState"];
            /**
             * Format: uuid
             * @description Identifier of the underlying device-side enrollment session
             *     created on `state=command_sent`. Use it to query
             *     `/biometry/enrollment-sessions/{sessionId}` device-side
             *     frame artefacts.
             */
            enrollmentSessionId?: string;
            /**
             * Format: uuid
             * @description Identifier of the resulting face template; set on `state=succeeded`.
             */
            templateId?: string;
            lastError?: components["schemas"]["EnrollmentLaunchError"];
            /** @description Number of `retry` operations applied to this launch. */
            retryCount: number;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /**
         * @description Availability of a channel for new launches:
         *     * `online` — device/station reachable and idle;
         *     * `busy` — currently servicing another launch;
         *     * `degraded` — reachable but reporting degraded capture (low
         *       camera quality, low light, etc.); the channel may be used but
         *       launches are more likely to land in `quality_failed`;
         *     * `offline` — not reachable; cannot be picked.
         * @enum {string}
         */
        EnrollmentChannelAvailability: "online" | "busy" | "degraded" | "offline";
        EnrollmentChannel: {
            kind: components["schemas"]["EnrollmentChannelKind"];
            target: components["schemas"]["EnrollmentLaunchTarget"];
            availability: components["schemas"]["EnrollmentChannelAvailability"];
            /** @description Operator-facing channel label (device or station name). */
            displayName?: string;
            /** Format: date-time */
            lastSeenAt?: string;
        };
        EnrollmentChannelsPage: {
            items: components["schemas"]["EnrollmentChannel"][];
        };
        EnrollmentCancelRequest: {
            /** @description Operator-supplied reason for cancellation (audit-only). */
            reason?: string;
        };
        EnrollmentRetryRequest: {
            /** @description Operator-supplied reason for retry (audit-only). */
            reason?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including IDEMPOTENCY_CONFLICT. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        SessionIdPath: string;
        LaunchIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    biometryEnrollmentChannelsList: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrollment channels page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentChannelsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentLaunch: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentLaunchRequest"];
            };
        };
        responses: {
            /** @description Enrollment launch created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentLaunch"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentLaunchGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                launchId: components["parameters"]["LaunchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrollment launch. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentLaunch"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentLaunchCancel: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                launchId: components["parameters"]["LaunchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EnrollmentCancelRequest"];
            };
        };
        responses: {
            /** @description Enrollment launch after cancellation. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentLaunch"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentLaunchRetry: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                launchId: components["parameters"]["LaunchIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EnrollmentRetryRequest"];
            };
        };
        responses: {
            /** @description Enrollment launch after retry dispatch. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentLaunch"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentSessionStart: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentSessionStart"];
            };
        };
        responses: {
            /** @description Enrollment session created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentFrameUpload: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameUpload"];
            };
        };
        responses: {
            /** @description Frame accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryEnrollmentFinalize: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Face template created. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaceTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryVerificationSessionStart: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationSessionStart"];
            };
        };
        responses: {
            /** @description Verification session created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryVerificationFrameUpload: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameUpload"];
            };
        };
        responses: {
            /** @description Frame accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryVerificationFinalize: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification decision. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationDecision"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    biometryPassiveCheck: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PassiveFaceCheckRequest"];
            };
        };
        responses: {
            /** @description Passive check recorded. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassiveFaceCheck"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
