/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/candidate-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List candidates with cursor pagination. */
        get: operations["candidatesList"];
        put?: never;
        /** Register a new candidate. */
        post: operations["candidateRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        /** Get a candidate by id. */
        get: operations["candidateGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidateId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change candidate status. */
        post: operations["candidateChangeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidateId}/enrollment-state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update candidate biometric enrollment state.
         * @description Push-update of the candidate's biometric enrollment
         *     state from `biometry-service`. Carries ONLY the
         *     resulting state, an optional reference to the upstream
         *     `enrollment_launches.id`, and a timestamp — no
         *     biometric content (embeddings, photos, liveness
         *     artifacts) is ever transmitted through this endpoint.
         *     Idempotent: re-issuing the same target state for the
         *     same `Idempotency-Key` is a no-op (no outbox event
         *     emitted on identical state).
         */
        post: operations["candidateChangeEnrollmentState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidateId}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soft-delete a candidate.
         * @description Idempotent soft-delete. Hard removal is out of scope of the public API.
         */
        post: operations["candidateDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Machine-readable error code in UPPER_SNAKE_CASE. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
        };
        /** @enum {string} */
        CandidateStatus: "registered" | "active" | "suspended" | "archived" | "deleted";
        IdentityDocument: {
            /** @enum {string} */
            documentType: "passport" | "idCard" | "drivingLicense" | "foreignPassport";
            documentNumber: string;
            /** Format: date */
            issuedOn?: string;
            /** Format: date */
            expiresOn?: string;
        };
        CandidateRegistration: {
            firstName: string;
            lastName: string;
            middleName?: string;
            /** Format: date */
            birthDate: string;
            identityDocument: components["schemas"]["IdentityDocument"];
            /** @description Optional reference id from an external traffic-police registry; not used as primary key. */
            externalRegistryId?: string;
        };
        /**
         * @description Candidate-side mirror of the biometric enrollment
         *     lifecycle. The authoritative state lives in
         *     `biometry-service`; this enum is the minimum
         *     projection candidate-service needs to publish so the
         *     operator UI can route the candidate to
         *     (re-)enrollment.
         * @enum {string}
         */
        CandidateEnrollmentState: "notStarted" | "pending" | "completed" | "failed" | "expired";
        /**
         * @description Push update of the candidate's enrollment state from
         *     `biometry-service`. Carries no biometric content. The
         *     optional `enrollmentLaunchId` is the foreign reference
         *     to the upstream `enrollment_launches.id` row.
         */
        CandidateEnrollmentStateChange: {
            targetState: components["schemas"]["CandidateEnrollmentState"];
            /** Format: uuid */
            enrollmentLaunchId?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        Candidate: {
            /** Format: uuid */
            candidateId: string;
            firstName: string;
            lastName: string;
            middleName?: string;
            /** Format: date */
            birthDate: string;
            identityDocument: components["schemas"]["IdentityDocument"];
            externalRegistryId?: string;
            status: components["schemas"]["CandidateStatus"];
            /** Format: date-time */
            statusChangedAt?: string;
            statusChangedBy?: components["schemas"]["ActorContext"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
            enrollmentState: components["schemas"]["CandidateEnrollmentState"];
            /** Format: uuid */
            enrollmentLaunchId?: string;
            /** Format: date-time */
            lastEnrollmentUpdatedAt?: string;
        };
        CandidateStatusChange: {
            targetStatus: components["schemas"]["CandidateStatus"];
            reason: string;
        };
        CandidateDeletion: {
            reason?: string;
        };
        CandidatesPage: {
            items: components["schemas"]["Candidate"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including idempotency conflicts (IDEMPOTENCY_CONFLICT). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
        CorrelationId: string;
        /** @description Idempotency key for non-idempotent command. Scope follows common-dto-and-error-model.md. */
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
        SortBy: "createdAt" | "lastName";
        SortOrder: "asc" | "desc";
        CandidateIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. Server may generate a new one if absent in request. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    candidatesList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortBy?: components["parameters"]["SortBy"];
                sortOrder?: components["parameters"]["SortOrder"];
                status?: components["schemas"]["CandidateStatus"];
                createdAtFrom?: string;
                createdAtTo?: string;
            };
            header?: {
                /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidates page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    candidateRegister: {
        parameters: {
            query?: never;
            header: {
                /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                /** @description Idempotency key for non-idempotent command. Scope follows common-dto-and-error-model.md. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateRegistration"];
            };
        };
        responses: {
            /** @description Candidate registered. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    candidateGet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidate. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    candidateChangeStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                /** @description Idempotency key for non-idempotent command. Scope follows common-dto-and-error-model.md. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateStatusChange"];
            };
        };
        responses: {
            /** @description Candidate after status change. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    candidateChangeEnrollmentState: {
        parameters: {
            query?: never;
            header: {
                /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                /** @description Idempotency key for non-idempotent command. Scope follows common-dto-and-error-model.md. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateEnrollmentStateChange"];
            };
        };
        responses: {
            /** @description Candidate after enrollment state update. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    candidateDelete: {
        parameters: {
            query?: never;
            header: {
                /** @description Logical correlation id (UUID v4) for end-to-end tracing. */
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                /** @description Idempotency key for non-idempotent command. Scope follows common-dto-and-error-model.md. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                candidateId: components["parameters"]["CandidateIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CandidateDeletion"];
            };
        };
        responses: {
            /** @description Candidate after deletion. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
