/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/exam-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an exam. */
        post: operations["examCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        /** Get an exam by id. */
        get: operations["examGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an exam. */
        post: operations["examStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish an exam with outcome. */
        post: operations["examFinish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort an exam. */
        post: operations["examAbort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        /** Get the exam's assigned exercises. */
        get: operations["examExercisesGet"];
        /** Replace the exam's assigned exercises (snapshot of catalog version refs). */
        put: operations["examExercisesAssign"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/telemetry-links": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a telemetry-session reference to an exam. */
        post: operations["examTelemetryLinkAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/violation-links": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a violation-fact reference snapshot to an exam. */
        post: operations["examViolationLinkAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/evidence-summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        /** Exam evidence summary (telemetry + violation references). */
        get: operations["examEvidenceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/evidence-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record an immutable evidence reference (media/audio/biometry/…) on an exam. */
        post: operations["examEvidenceEventAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/evidence-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        /** Composed exam evidence timeline (lifecycle + external references), keyset-paginated. */
        get: operations["examEvidenceTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/calculate-result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate the final exam result (idempotent; requires completed lifecycle). */
        post: operations["examResultCalculate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        /** Get the calculated exam result. */
        get: operations["examResultGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        /** Get the exam event timeline (paginated). */
        get: operations["examTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
            /** Format: uuid */
            vehicleId?: string;
        };
        /** @description Reference to a candidate owned by `candidate-service`. Only id is exchanged. */
        CandidateRef: {
            /** Format: uuid */
            candidateId: string;
        };
        /** @description Reference to a vehicle owned by `vehicle-service`. Only id is exchanged. */
        VehicleRef: {
            /** Format: uuid */
            vehicleId: string;
        };
        /** @enum {string} */
        ExamType: "autodromeBasic" | "autodromeAdvanced" | "retest";
        /** @enum {string} */
        ExamStatus: "scheduled" | "inProgress" | "finished" | "aborted";
        /** @enum {string} */
        ExamOutcome: "passed" | "failed";
        ExamCreation: {
            candidateRef: components["schemas"]["CandidateRef"];
            vehicleRef: components["schemas"]["VehicleRef"];
            examType: components["schemas"]["ExamType"];
            /** Format: date-time */
            scheduledAt: string;
            notes?: string;
        };
        ExamStart: {
            notes?: string;
        };
        ExamFinish: {
            outcome: components["schemas"]["ExamOutcome"];
            score?: number;
            notes?: string;
        };
        ExamAbort: {
            reason: string;
        };
        Exam: {
            /** Format: uuid */
            examId: string;
            candidateRef: components["schemas"]["CandidateRef"];
            vehicleRef: components["schemas"]["VehicleRef"];
            examType: components["schemas"]["ExamType"];
            status: components["schemas"]["ExamStatus"];
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            outcome?: components["schemas"]["ExamOutcome"];
            score?: number;
            examiner?: components["schemas"]["ActorContext"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description Reference snapshot to an exercise catalog version owned by
         *     `exercise-service`. Only the reference (id + optional pinned
         *     version + optional display code/title) is stored; the catalog is
         *     never copied.
         */
        ExerciseAssignmentItem: {
            /** Format: uuid */
            exerciseId: string;
            /** Format: uuid */
            exerciseVersionId?: string;
            versionNumber?: number;
            code?: string;
            title?: string;
        };
        /** @description Replace-the-whole-set request for an exam's assigned exercises. */
        ExamExerciseAssignmentRequest: {
            exercises: components["schemas"]["ExerciseAssignmentItem"][];
        };
        AssignedExercise: {
            /** Format: uuid */
            exerciseId: string;
            /** Format: uuid */
            exerciseVersionId?: string;
            versionNumber?: number;
            code?: string;
            title?: string;
            orderIndex: number;
        };
        ExamExerciseAssignment: {
            /** Format: uuid */
            examId: string;
            exercises: components["schemas"]["AssignedExercise"][];
            /** Format: date-time */
            assignedAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @enum {string} */
        ExamViolationSeverity: "low" | "medium" | "high" | "critical";
        ExamTelemetryLinkRequest: {
            /** Format: uuid */
            telemetrySessionId: string;
            /** Format: uuid */
            vehicleId?: string;
        };
        ExamTelemetryLink: {
            /** Format: uuid */
            telemetrySessionId: string;
            /** Format: uuid */
            vehicleId?: string;
            /** Format: date-time */
            linkedAt: string;
        };
        ExamViolationLinkRequest: {
            /** Format: uuid */
            factId: string;
            /** Format: uuid */
            violationId: string;
            violationCode: string;
            severity: components["schemas"]["ExamViolationSeverity"];
            ruleVersion: number;
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            telemetrySessionId?: string;
        };
        ExamViolationLink: {
            /** Format: uuid */
            factId: string;
            /** Format: uuid */
            violationId: string;
            violationCode: string;
            severity: components["schemas"]["ExamViolationSeverity"];
            ruleVersion: number;
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            telemetrySessionId?: string;
            /** Format: date-time */
            linkedAt: string;
        };
        ExamEvidenceSummary: {
            /** Format: uuid */
            examId: string;
            telemetrySessions: components["schemas"]["ExamTelemetryLink"][];
            violations: components["schemas"]["ExamViolationLink"][];
            violationCount: number;
        };
        ExamEvidenceEventRequest: {
            sourceType: string;
            refKind: string;
            refId: string;
            /** Format: date-time */
            occurredAt: string;
            label?: string;
            severity?: string;
        };
        ExamEvidenceTimelineEntry: {
            sourceType: string;
            /** Format: date-time */
            occurredAt: string;
            refKind: string;
            refId?: string;
            label?: string;
            severity?: string;
        };
        ExamEvidenceTimelinePage: {
            items: components["schemas"]["ExamEvidenceTimelineEntry"][];
            nextPageToken?: string;
        };
        ExamResult: {
            /** Format: uuid */
            examId: string;
            result: components["schemas"]["ExamOutcome"];
            score?: number;
            violationCount: number;
            criticalViolationCount: number;
            calculatedFromStatus: components["schemas"]["ExamStatus"];
            /** Format: date-time */
            calculatedAt: string;
        };
        /** @enum {string} */
        ExamTimelineEventType: "examCreated" | "examStarted" | "examFinished" | "examAborted" | "violationRecorded" | "mediaSegmentAttached" | "reportGenerated";
        ExamTimelineEvent: {
            /** Format: uuid */
            eventId: string;
            eventType: components["schemas"]["ExamTimelineEventType"];
            /** Format: date-time */
            eventTime: string;
            actor?: components["schemas"]["ActorContext"];
            /**
             * @description Event-specific structured details. Schema per event type is defined in
             *     `contracts/events/`; here it is opaque.
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        ExamTimelinePage: {
            items: components["schemas"]["ExamTimelineEvent"][];
            nextPageToken?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including IDEMPOTENCY_CONFLICT. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
        SortOrder: "asc" | "desc";
        ExamIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    examCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamCreation"];
            };
        };
        responses: {
            /** @description Exam created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examStart: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExamStart"];
            };
        };
        responses: {
            /** @description Exam after start. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examFinish: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamFinish"];
            };
        };
        responses: {
            /** @description Exam after finish. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examAbort: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamAbort"];
            };
        };
        responses: {
            /** @description Exam after abort. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examExercisesGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment snapshot. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamExerciseAssignment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examExercisesAssign: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamExerciseAssignmentRequest"];
            };
        };
        responses: {
            /** @description Assignment snapshot after replace. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamExerciseAssignment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examTelemetryLinkAdd: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamTelemetryLinkRequest"];
            };
        };
        responses: {
            /** @description Already linked. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTelemetryLink"];
                };
            };
            /** @description Telemetry link created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTelemetryLink"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examViolationLinkAdd: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamViolationLinkRequest"];
            };
        };
        responses: {
            /** @description Already linked. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamViolationLink"];
                };
            };
            /** @description Violation link created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamViolationLink"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examEvidenceSummary: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence summary. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamEvidenceSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examEvidenceEventAdd: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamEvidenceEventRequest"];
            };
        };
        responses: {
            /** @description Already recorded. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Evidence reference recorded. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examEvidenceTimeline: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence timeline page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamEvidenceTimelinePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examResultCalculate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result already calculated (replay). */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResult"];
                };
            };
            /** @description Result calculated. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examResultGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calculated result. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examTimeline: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortOrder?: components["parameters"]["SortOrder"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: components["parameters"]["ExamIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam timeline page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTimelinePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
