/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/exercise-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exercises with cursor pagination. */
        get: operations["exercisesList"];
        put?: never;
        /** Create a new exercise (draft). */
        post: operations["exerciseCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
            };
            cookie?: never;
        };
        /** Get an exercise by id. */
        get: operations["exerciseGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a new version of an exercise.
         * @description Materialises a new immutable `ExerciseVersion` from the current
         *     draft. The previous published version remains addressable by
         *     `versionId`; historical exams that reference the old version
         *     stay reproducible.
         */
        post: operations["exercisePublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
                versionId: string;
            };
            cookie?: never;
        };
        /**
         * Get a specific exercise version.
         * @description Reproducible snapshot of an exercise as published at a specific
         *     version. Historical exams resolve their `exerciseVersionId`
         *     through this endpoint.
         */
        get: operations["exerciseVersionGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercise-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exercise groups. */
        get: operations["exerciseGroupsList"];
        put?: never;
        /** Create an exercise group. */
        post: operations["exerciseGroupCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description UPPER_SNAKE_CASE machine-readable code. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @enum {string} */
        ExerciseStatus: "draft" | "published" | "archived";
        /** @enum {string} */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * @description Reference to a violation rule owned by `violation-rule-service`.
         *     `ruleVersion` is included so the link is reproducible after a
         *     rule re-publish.
         */
        RuleRef: {
            /** Format: uuid */
            ruleId: string;
            ruleVersion: number;
        };
        /**
         * @description Reference to a geometry primitive/area owned by
         *     `autodrome-geometry-service`.
         */
        GeometryRef: {
            /** Format: uuid */
            geometryId: string;
            geometryVersion?: number;
        };
        /**
         * @description Reference to a driving-category complex owned by
         *     `reference-data-service`.
         */
        CategoryRef: {
            /** Format: uuid */
            categoryId: string;
        };
        /**
         * @description Error definition embedded in an exercise version. Each error
         *     references the rule that detects it.
         */
        ExerciseError: {
            /** Format: uuid */
            errorId: string;
            code: string;
            title: string;
            severity: components["schemas"]["Severity"];
            ruleRef?: components["schemas"]["RuleRef"];
        };
        ExerciseCreation: {
            code: string;
            title: string;
            description?: string;
        };
        /**
         * @description Body of `POST /exercises/{exerciseId}/publish`. Materialises
         *     a new immutable `ExerciseVersion`.
         */
        ExerciseVersionDraft: {
            rulesRefs: components["schemas"]["RuleRef"][];
            geometryRefs: components["schemas"]["GeometryRef"][];
            errors: components["schemas"]["ExerciseError"][];
            notes?: string;
        };
        Exercise: {
            /** Format: uuid */
            exerciseId: string;
            code: string;
            title: string;
            description?: string;
            status: components["schemas"]["ExerciseStatus"];
            currentVersion?: {
                /** Format: uuid */
                versionId: string;
                versionNumber: number;
                /** Format: date-time */
                publishedAt?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ExerciseVersion: {
            /** Format: uuid */
            versionId: string;
            /** Format: uuid */
            exerciseId: string;
            versionNumber: number;
            /** Format: date-time */
            publishedAt: string;
            publishedBy?: components["schemas"]["ActorContext"];
            rulesRefs: components["schemas"]["RuleRef"][];
            geometryRefs: components["schemas"]["GeometryRef"][];
            errors: components["schemas"]["ExerciseError"][];
            notes?: string;
        };
        ExercisesPage: {
            items: components["schemas"]["Exercise"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
        ExerciseGroupCreation: {
            title: string;
            /** @description Ordered list of exercise refs that make up this group. */
            exerciseOrder: {
                /** Format: uuid */
                exerciseId: string;
                /** Format: uuid */
                exerciseVersionId?: string;
            }[];
            categoryRefs: components["schemas"]["CategoryRef"][];
        };
        ExerciseGroup: {
            /** Format: uuid */
            groupId: string;
            title: string;
            exerciseOrder: {
                /** Format: uuid */
                exerciseId: string;
                /** Format: uuid */
                exerciseVersionId?: string;
            }[];
            categoryRefs: components["schemas"]["CategoryRef"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ExerciseGroupsPage: {
            items: components["schemas"]["ExerciseGroup"][];
            nextPageToken?: string;
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
            /** Format: uuid */
            vehicleId?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including IDEMPOTENCY_CONFLICT. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
        SortBy: "createdAt" | "code" | "title";
        SortOrder: "asc" | "desc";
        ExerciseIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exercisesList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortBy?: components["parameters"]["SortBy"];
                sortOrder?: components["parameters"]["SortOrder"];
                status?: components["schemas"]["ExerciseStatus"];
                code?: string;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercises page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisesPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exerciseCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreation"];
            };
        };
        responses: {
            /** @description Exercise created (status=draft). */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exerciseGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exercisePublish: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseVersionDraft"];
            };
        };
        responses: {
            /** @description Exercise after publish (status=published, currentVersion updated). */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exerciseVersionGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise version. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseVersion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exerciseGroupsList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise groups page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseGroupsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exerciseGroupCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseGroupCreation"];
            };
        };
        responses: {
            /** @description Exercise group created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
