/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/identity-security-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate an employee and issue a token pair.
         * @description Validates employee credentials and returns an access/refresh
         *     token pair. This is a public endpoint and does not require a
         *     bearer token; the `security` requirement is relaxed per
         *     operation.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair.
         * @description Rotates the refresh token. The previous refresh token is
         *     invalidated server-side; this operation is intentionally NOT
         *     idempotent (token rotation) and therefore carries no
         *     `Idempotency-Key`.
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session.
         * @description Revokes the supplied refresh token (and its session).
         *     Idempotent by nature — logging out an already-revoked token
         *     returns `204`.
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Introspect a token for the gateway or internal services.
         * @description Validation-only POST (the token travels in the body, never in
         *     the URL). Returns whether the token is active and, when
         *     active, its subject and scopes. Non-mutating, so it carries no
         *     `Idempotency-Key`. Intended for `api-gateway-bff` and
         *     service-to-service callers.
         */
        post: operations["authIntrospect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current authenticated actor.
         * @description Resolves the bearer token to the acting subject with its
         *     effective roles and permissions.
         */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a device token via service command.
         * @description Called by `android-device-management-service` to mint a token
         *     bound to a device and a binding context (station / vehicle /
         *     exam). Mutating command — requires `Idempotency-Key`; replays
         *     with the same key and body return the original token reference.
         */
        post: operations["deviceTokenIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens/{tokenId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: components["parameters"]["TokenIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke an issued token.
         * @description Revokes an access/refresh/device token by id. Mutating
         *     command — requires `Idempotency-Key`. Revoking an
         *     already-revoked token returns the same revocation record
         *     (idempotent terminal state).
         */
        post: operations["tokenRevoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description UPPER_SNAKE_CASE machine-readable code. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /**
         * @description Kind of access subject:
         *     - `user` — employee account;
         *     - `service` — internal backend service client;
         *     - `device` — Android device / kiosk;
         *     - `system` — pre-assigned system actor.
         * @enum {string}
         */
        ActorType: "user" | "service" | "device" | "system";
        /**
         * @description Subject kind a token authenticates.
         * @enum {string}
         */
        SubjectType: "user" | "service" | "device";
        /**
         * @description Employee role model. Covers the full set required by the
         *     service architecture.
         * @enum {string}
         */
        Role: "admin" | "operator" | "inspector" | "dispatcher" | "auditor" | "techAdmin";
        /**
         * @description Context a device token is bound to:
         *     - `station` — autodrome station;
         *     - `vehicle` — a specific vehicle;
         *     - `exam` — a specific exam context.
         * @enum {string}
         */
        BindingType: "station" | "vehicle" | "exam";
        LoginRequest: {
            login: string;
            password: string;
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /**
             * Format: date-time
             * @description Expiry of the access token (UTC).
             */
            expiresAt: string;
            scopes: string[];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        IntrospectRequest: {
            token: string;
        };
        TokenIntrospection: {
            /**
             * @description True if the token is valid and not expired/revoked. When
             *     false, the remaining fields are omitted.
             */
            active: boolean;
            /** Format: uuid */
            subjectId?: string;
            subjectType?: components["schemas"]["SubjectType"];
            scopes?: string[];
            /** Format: date-time */
            expiresAt?: string;
        };
        Actor: {
            /** Format: uuid */
            actorId: string;
            actorType: components["schemas"]["ActorType"];
            roles: components["schemas"]["Role"][];
            /** @description Effective permission keys granted by the roles. */
            permissions: string[];
        };
        DeviceTokenIssueRequest: {
            /** Format: uuid */
            deviceId: string;
            role: components["schemas"]["Role"];
            bindingType: components["schemas"]["BindingType"];
            /**
             * Format: uuid
             * @description Id of the bound station / vehicle / exam.
             */
            bindingId: string;
            /**
             * @description Requested token lifetime in seconds. Named with an
             *     explicit unit; this is a TTL, not an instant. The server
             *     returns the resolved `expiresAt` instant on the response.
             */
            ttlSeconds: number;
        };
        DeviceToken: {
            /** Format: uuid */
            tokenId: string;
            /** Format: uuid */
            deviceId: string;
            accessToken: string;
            role: components["schemas"]["Role"];
            bindingType: components["schemas"]["BindingType"];
            /** Format: uuid */
            bindingId: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            issuedAt: string;
        };
        TokenRevokeRequest: {
            /** @description Audit note for the revocation. */
            reason?: string;
        };
        TokenRevocation: {
            /** Format: uuid */
            tokenId: string;
            revoked: boolean;
            /** Format: date-time */
            revokedAt: string;
            reason?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Authentication missing or invalid. Common codes:
         *     `AUTH_INVALID_CREDENTIALS`, `AUTH_TOKEN_EXPIRED`,
         *     `AUTH_TOKEN_INVALID`, `AUTH_TOKEN_REVOKED`,
         *     `AUTH_REFRESH_TOKEN_INVALID`.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed (`AUTH_FORBIDDEN`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Conflicting state. Common codes: `IDEMPOTENCY_CONFLICT`,
         *     `IDENTITY_TOKEN_ALREADY_REVOKED`, `IDENTITY_BINDING_INVALID`.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed (`VALIDATION_FAILED`). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        TokenIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLogin: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication succeeded. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token pair refreshed. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Session ended. */
            204: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authIntrospect: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntrospectRequest"];
            };
        };
        responses: {
            /** @description Introspection result. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenIntrospection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deviceTokenIssue: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenIssueRequest"];
            };
        };
        responses: {
            /** @description Device token issued. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    tokenRevoke: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tokenId: components["parameters"]["TokenIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TokenRevokeRequest"];
            };
        };
        responses: {
            /** @description Token revoked. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRevocation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
