/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/media-archive-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/media/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a recording session for an exam. */
        post: operations["mediaRecordingStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/recordings/{recordingId}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a segment for a recording.
         * @description Segment bytes are not transmitted via this API; the request references
         *     the stored object by `objectKey`. Object upload mechanics are out of
         *     scope of this spec.
         */
        post: operations["mediaSegmentRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/recordings/{recordingId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize a recording. */
        post: operations["mediaRecordingFinalize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/recordings/{recordingId}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: components["parameters"]["RecordingIdPath"];
            };
            cookie?: never;
        };
        /** Get a playback manifest for a recording. */
        get: operations["mediaRecordingManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/exams/{examId}/media": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        /** Look up evidence media (recordings) for an exam. */
        get: operations["mediaExamLookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an export package across one or more recordings. */
        post: operations["mediaExportCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @description Reference to exam-service entity. Id-only. */
        ExamRef: {
            /** Format: uuid */
            examId: string;
        };
        MediaSource: {
            sourceId: string;
            /** @enum {string} */
            kind: "cabinFront" | "cabinSide" | "exteriorFront" | "exteriorRear" | "microphone";
        };
        /** @enum {string} */
        MediaRecordingStatus: "active" | "finalized" | "failed";
        MediaRecordingStart: {
            examRef: components["schemas"]["ExamRef"];
            sources: components["schemas"]["MediaSource"][];
            /** Format: uuid */
            sessionId?: string;
            evidenceType?: string;
        };
        MediaRecording: {
            /** Format: uuid */
            recordingId: string;
            examRef: components["schemas"]["ExamRef"];
            sources: components["schemas"]["MediaSource"][];
            status: components["schemas"]["MediaRecordingStatus"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finalizedAt?: string;
            /** Format: uuid */
            sessionId?: string;
            evidenceType?: string;
        };
        ExamMediaRecording: {
            /** Format: uuid */
            recordingId: string;
            /** Format: uuid */
            sessionId?: string;
            evidenceType?: string;
            status: components["schemas"]["MediaRecordingStatus"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finalizedAt?: string;
            segmentCount: number;
        };
        ExamMediaIndex: {
            /** Format: uuid */
            examId: string;
            recordings: components["schemas"]["ExamMediaRecording"][];
        };
        MediaSegmentRegister: {
            sourceId: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** @description Opaque storage key for the segment object; storage backend not part of the contract. */
            objectKey: string;
            /** @description Hex-encoded SHA-256 of the segment object. */
            checksum: string;
        };
        MediaSegment: {
            /** Format: uuid */
            segmentId: string;
            /** Format: uuid */
            recordingId: string;
            sourceId: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            objectKey: string;
            checksum: string;
        };
        PlaybackManifestEntry: {
            sourceId: string;
            segments: components["schemas"]["MediaSegment"][];
        };
        PlaybackTimelineMapping: {
            /** Format: date-time */
            timelineFrom: string;
            /** Format: date-time */
            timelineTo: string;
            sourceId: string;
            /** Format: uuid */
            segmentId: string;
        };
        PlaybackManifest: {
            /** Format: uuid */
            recordingId: string;
            segments: components["schemas"]["PlaybackManifestEntry"][];
            timelineMap: components["schemas"]["PlaybackTimelineMapping"][];
            /** Format: date-time */
            expiresAt: string;
        };
        /** @enum {string} */
        MediaExportFormat: "mp4" | "zip";
        /** @enum {string} */
        MediaExportStatus: "accepted" | "inProgress" | "ready" | "failed";
        MediaExportRequest: {
            recordingIds: string[];
            format: components["schemas"]["MediaExportFormat"];
            /** Format: date-time */
            timeRangeFrom?: string;
            /** Format: date-time */
            timeRangeTo?: string;
        };
        MediaExport: {
            /** Format: uuid */
            exportId: string;
            recordingIds: string[];
            format: components["schemas"]["MediaExportFormat"];
            status: components["schemas"]["MediaExportStatus"];
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            readyAt?: string;
            /** @description Opaque reference to produced export object. Populated when status=ready. */
            artifactRef?: string;
            /** @description Hex-encoded SHA-256 of the export artifact. */
            checksum?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including IDEMPOTENCY_CONFLICT. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        RecordingIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    mediaRecordingStart: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaRecordingStart"];
            };
        };
        responses: {
            /** @description Recording started. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaRecording"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    mediaSegmentRegister: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                recordingId: components["parameters"]["RecordingIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaSegmentRegister"];
            };
        };
        responses: {
            /** @description Segment registered. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSegment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    mediaRecordingFinalize: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                recordingId: components["parameters"]["RecordingIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording after finalize. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaRecording"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    mediaRecordingManifest: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                recordingId: components["parameters"]["RecordingIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback manifest. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackManifest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    mediaExamLookup: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam media index. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamMediaIndex"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    mediaExportCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaExportRequest"];
            };
        };
        responses: {
            /** @description Export accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaExport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
