/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/reference-data-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/reference/{dictionary}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dictionary: components["parameters"]["DictionaryPath"];
            };
            cookie?: never;
        };
        /** Get a dictionary's items. */
        get: operations["referenceGet"];
        put?: never;
        /** Add an item to a dictionary. */
        post: operations["referenceItemAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reference/{dictionary}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dictionary: components["parameters"]["DictionaryPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a new dictionary version. */
        post: operations["referencePublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ReferenceItemCreate: {
            code: string;
            title: string;
            /** Format: date */
            validFrom?: string;
            /** Format: date */
            validTo?: string;
        };
        ReferenceItem: {
            dictionary: string;
            /** Format: uuid */
            itemId: string;
            code: string;
            title: string;
            /** Format: date */
            validFrom?: string;
            /** Format: date */
            validTo?: string;
        };
        ReferenceDictionary: {
            dictionary: string;
            version?: number;
            items: components["schemas"]["ReferenceItem"][];
        };
        ReferenceVersion: {
            dictionary: string;
            version: number;
            checksum: string;
            /** Format: date-time */
            publishedAt: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Dictionary not found (REFERENCE_DICTIONARY_NOT_FOUND). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflict. IDEMPOTENCY_CONFLICT, REFERENCE_ITEM_DUPLICATE, REFERENCE_NOTHING_TO_PUBLISH. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        DictionaryPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    referenceGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                dictionary: components["parameters"]["DictionaryPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dictionary items. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceDictionary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    referenceItemAdd: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                dictionary: components["parameters"]["DictionaryPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceItemCreate"];
            };
        };
        responses: {
            /** @description Item added. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    referencePublish: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                dictionary: components["parameters"]["DictionaryPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version published. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceVersion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
