/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/scheduling-integration-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/schedules/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a schedule. */
        post: operations["scheduleImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List schedules. */
        get: operations["schedulesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: components["parameters"]["ScheduleIdPath"];
            };
            cookie?: never;
        };
        /** Get a schedule. */
        get: operations["scheduleGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration states. */
        get: operations["integrationsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{integrationId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integrationId: components["parameters"]["IntegrationIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry an integration. */
        post: operations["integrationRetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ExternalRef: {
            system: string;
            type?: string;
            externalId: string;
            localRef?: string;
        };
        ScheduleImportRequest: {
            source: string;
            /** @enum {string} */
            format: "json" | "csv" | "legacy";
            payloadRef?: string;
            dryRun: boolean;
            candidates?: string[];
            exams?: string[];
            externalRefs?: components["schemas"]["ExternalRef"][];
        };
        ScheduleImportResult: {
            /** Format: uuid */
            scheduleId: string;
            source: string;
            dryRun: boolean;
            candidateCount: number;
            examCount: number;
            /** Format: date-time */
            importedAt: string;
        };
        Schedule: {
            /** Format: uuid */
            scheduleId: string;
            source: string;
            /** Format: date */
            scheduleDate?: string;
            candidates: string[];
            exams: string[];
            externalRefs: components["schemas"]["ExternalRef"][];
            /** Format: date-time */
            createdAt?: string;
        };
        SchedulesPage: {
            items: components["schemas"]["Schedule"][];
            nextPageToken?: string;
        };
        IntegrationState: {
            /** Format: uuid */
            integrationId: string;
            system?: string;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "retrying";
            attempts: number;
            lastError?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        IntegrationStatusPage: {
            items: components["schemas"]["IntegrationState"][];
        };
        IntegrationAttempt: {
            /** Format: uuid */
            attemptId: string;
            /** Format: uuid */
            integrationId: string;
            status: string;
            error?: string;
            /** Format: date-time */
            occurredAt: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflict. IDEMPOTENCY_CONFLICT, INTEGRATION_NOT_RETRYABLE. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        ScheduleIdPath: string;
        IntegrationIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scheduleImport: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleImportRequest"];
            };
        };
        responses: {
            /** @description Import accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    schedulesList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedules page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulesPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    scheduleGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                scheduleId: components["parameters"]["ScheduleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    integrationsStatus: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration states. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    integrationRetry: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                integrationId: components["parameters"]["IntegrationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry scheduled. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAttempt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
