/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/traffic-control-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated traffic state. */
        get: operations["trafficState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traffic/controllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a traffic controller. */
        post: operations["trafficControllerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traffic/lights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a traffic light. */
        post: operations["trafficLightCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traffic/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a runtime command to a controller. */
        post: operations["trafficCommandSend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @enum {string} */
        ControllerStatus: "healthy" | "degraded" | "offline" | "unknown";
        TrafficControllerCreate: {
            address: string;
            capabilities?: string[];
        };
        TrafficController: {
            /** Format: uuid */
            controllerId: string;
            status: components["schemas"]["ControllerStatus"];
            address: string;
            capabilities?: string[];
        };
        TrafficLightCreate: {
            /** Format: uuid */
            controllerId: string;
            positionRef: string;
            state?: string;
        };
        TrafficLight: {
            /** Format: uuid */
            lightId: string;
            /** Format: uuid */
            controllerId: string;
            positionRef: string;
            state: string;
        };
        TrafficCommandCreate: {
            /** Format: uuid */
            controllerId: string;
            /** @enum {string} */
            commandType: "setProgram" | "setState" | "reset" | "blink";
            payload?: {
                [key: string]: unknown;
            };
            reason?: string;
        };
        TrafficCommandAccepted: {
            /** Format: uuid */
            commandId: string;
            /** Format: uuid */
            controllerId: string;
            commandType: string;
            /** Format: date-time */
            acceptedAt: string;
        };
        TrafficState: {
            controllers: components["schemas"]["TrafficController"][];
            lights: components["schemas"]["TrafficLight"][];
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflict. IDEMPOTENCY_CONFLICT, TRAFFIC_CONTROLLER_DEGRADED. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    trafficState: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Traffic state. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    trafficControllerCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrafficControllerCreate"];
            };
        };
        responses: {
            /** @description Controller created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficController"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    trafficLightCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrafficLightCreate"];
            };
        };
        responses: {
            /** @description Light created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficLight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    trafficCommandSend: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrafficCommandCreate"];
            };
        };
        responses: {
            /** @description Command accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficCommandAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
