/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/vehicle-simulator-rpi/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["simulatorHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe.
         * @description Reports whether the emulator can accept scenario commands:
         *     scenario catalog reachable AND parser configured.
         */
        get: operations["simulatorHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/scenarios/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load a legacy scenario into the emulator.
         * @description Loads the scenario referenced by `scenarioId` into the
         *     emulator. The semantic scenario model is shared with
         *     Web VirtualVehicle — the caller passes the same scenario
         *     identifier regardless of which runtime ultimately plays
         *     it. Format must be `legacyLiteReplay` or
         *     `legacyFullTrajectory`; other types are rejected.
         */
        post: operations["simulatorScenarioLoad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/playback/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start playback of the loaded scenario. */
        post: operations["simulatorPlaybackStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/playback/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause playback (state retained). */
        post: operations["simulatorPlaybackPause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/playback/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume paused playback. */
        post: operations["simulatorPlaybackResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/playback/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop playback and unload the current scenario. */
        post: operations["simulatorPlaybackStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current emulator runtime status. */
        get: operations["simulatorStatusGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/bridge/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bridge view for Android tablet + Web Console.
         * @description Read-only state of the RPi <-> tablet bridge. Reports
         *     connection status, the currently-bound tablet device id
         *     (foreign reference to `android-device-management-service`,
         *     registration handled THERE), and the active playback
         *     session id. NO command surface — start/pause/resume/stop
         *     live under `/simulator/playback/*`.
         */
        get: operations["simulatorBridgeStatusGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            reason?: string;
        };
        SimulatorReadinessDegraded: {
            /** @enum {string} */
            status: "degraded";
            /** @enum {string} */
            reason: "scenario_catalog_unreachable" | "parser_not_configured" | "hardware_bus_unreachable";
        };
        /**
         * @description Playback lifecycle of the emulator process:
         *     - `idle` — no scenario loaded;
         *     - `loaded` — scenario loaded but not yet started;
         *     - `playing` — playback running;
         *     - `paused` — playback paused, scenario retained;
         *     - `stopped` — last playback terminated, scenario unloaded;
         *     - `failed` — last command failed; emulator requires manual recovery.
         * @enum {string}
         */
        SimulatorPhase: "idle" | "loaded" | "playing" | "paused" | "stopped" | "failed";
        /**
         * @description Legacy-compatible scenario inputs accepted by the RPi
         *     emulator. Mirrors the `legacyLiteReplay` / `legacyFullTrajectory`
         *     values used by `virtual-vehicle-service`; web-only
         *     scenarios are rejected.
         * @enum {string}
         */
        SimulatorScenarioFormat: "legacyLiteReplay" | "legacyFullTrajectory";
        SimulatorScenarioLoad: {
            /**
             * Format: uuid
             * @description Foreign reference to the semantic scenario.
             */
            scenarioId: string;
            format: components["schemas"]["SimulatorScenarioFormat"];
            /**
             * @description When true, the emulator rewinds the loaded trajectory
             *     to the first sample. Defaults to true.
             */
            rewindToStart?: boolean;
        };
        SimulatorRuntimeStatus: {
            /**
             * Format: uuid
             * @description Stable per-process identifier.
             */
            emulatorId: string;
            phase: components["schemas"]["SimulatorPhase"];
            /** Format: uuid */
            loadedScenarioId?: string;
            loadedScenarioFormat?: components["schemas"]["SimulatorScenarioFormat"];
            /**
             * Format: uuid
             * @description Identifier of the current playback session, refreshed
             *     on each `start`. `null` while idle/stopped.
             */
            playbackSessionId?: string;
            /** Format: date-time */
            observedAt: string;
        };
        /** @enum {string} */
        SimulatorBridgeConnection: "disconnected" | "connecting" | "connected" | "degraded";
        SimulatorBridgeStatus: {
            /** Format: uuid */
            emulatorId: string;
            connection: components["schemas"]["SimulatorBridgeConnection"];
            /**
             * Format: uuid
             * @description Foreign reference to the
             *     `android-device-management-service` device record.
             *     Registration / unbinding happens THERE.
             */
            boundTabletDeviceId?: string;
            /** Format: uuid */
            activePlaybackSessionId?: string;
            /** Format: date-time */
            observedAt: string;
            /** @description Operator-facing degradation note. */
            reason?: string;
        };
        ErrorBody: {
            code: string;
            message: string;
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
            /** @description Optional structured details. */
            details?: unknown;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description Validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Caller is not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid state transition or idempotency conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Semantic validation failure. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unhandled simulator-side failure. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulatorHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    simulatorHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Degraded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorReadinessDegraded"];
                };
            };
        };
    };
    simulatorScenarioLoad: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulatorScenarioLoad"];
            };
        };
        responses: {
            /** @description Scenario accepted; emulator transitions to `loaded`. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorRuntimeStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description Scenario id is not known to the configured scenario
             *     source. Operator must register the scenario via
             *     `Simulator:Scenarios:*` configuration or wait for the
             *     production catalog client to ship.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    simulatorPlaybackStart: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorRuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    simulatorPlaybackPause: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback paused. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorRuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    simulatorPlaybackResume: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback resumed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorRuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    simulatorPlaybackStop: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback stopped. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorRuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    simulatorStatusGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorRuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    simulatorBridgeStatusGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bridge status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorBridgeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
