/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/vehicle-telemetry-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/telemetry/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a normalized telemetry batch.
         * @description Accepts a batch of normalized samples for one source. Mutating
         *     command — requires `Idempotency-Key`; replays of the same batch
         *     are deduplicated by `(sourceId, sampleSequence)`.
         */
        post: operations["telemetryIngestBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/gateways/{gatewayId}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gatewayId: components["parameters"]["GatewayIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a gateway heartbeat. */
        post: operations["telemetryGatewayHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/sessions/{sessionId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        /** Read a session telemetry timeline. */
        get: operations["telemetrySessionTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/vehicles/{vehicleId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        /** Read vehicle telemetry health. */
        get: operations["telemetryVehicleHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /**
         * @description Origin of the telemetry, normalized:
         *     - `vehicleEdgeGateway` — physical vehicle via edge gateway;
         *     - `virtualVehicle` — Web virtual vehicle emulator;
         *     - `rpiSimulator` — RPi simulator acting through the domain plane.
         * @enum {string}
         */
        SourceType: "vehicleEdgeGateway" | "virtualVehicle" | "rpiSimulator";
        /** @enum {string} */
        GatewayHealthStatus: "healthy" | "degraded" | "offline" | "unknown";
        TelemetrySignal: {
            /** @description Normalized signal code, e.g. speed or yaw. */
            code: string;
            value: number;
            unit?: string;
            confidence?: number;
        };
        TelemetrySample: {
            /** Format: int64 */
            sampleSequence: number;
            /** Format: date-time */
            capturedAt: string;
            signals?: components["schemas"]["TelemetrySignal"][];
            quality?: number;
        };
        TelemetryIngestBatch: {
            /** Format: uuid */
            batchId: string;
            sourceType: components["schemas"]["SourceType"];
            /**
             * Format: uuid
             * @description Gateway/source id.
             */
            sourceId: string;
            /** Format: uuid */
            vehicleId: string;
            /** Format: uuid */
            examId?: string;
            /** @enum {string} */
            coordinateFrame: "legacyXY" | "normalizedXY" | "geodeticWgs84";
            /** Format: date-time */
            sentAt?: string;
            samples: components["schemas"]["TelemetrySample"][];
        };
        TelemetryBatchAccepted: {
            /** Format: uuid */
            batchId: string;
            /** Format: uuid */
            telemetrySessionId: string;
            acceptedSampleCount: number;
            duplicateCount?: number;
            duplicate: boolean;
            /** Format: int64 */
            firstSampleSequence: number;
            /** Format: int64 */
            lastSampleSequence: number;
        };
        GatewayHeartbeat: {
            /** Format: uuid */
            gatewayId: string;
            status: components["schemas"]["GatewayHealthStatus"];
            /** Format: date-time */
            observedAt: string;
        };
        GatewayHeartbeatAccepted: {
            /** Format: uuid */
            gatewayId: string;
            duplicate: boolean;
            healthStatus: components["schemas"]["GatewayHealthStatus"];
            /** Format: date-time */
            observedAt: string;
        };
        TelemetryGap: {
            /** Format: int64 */
            fromSequence: number;
            /** Format: int64 */
            toSequence: number;
            reason: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high";
        };
        TelemetryTimeline: {
            /** Format: uuid */
            telemetrySessionId: string;
            /** Format: uuid */
            vehicleId: string;
            /** Format: uuid */
            examId?: string;
            coordinateFrame: string;
            sampleCount: number;
            samples: components["schemas"]["TelemetrySample"][];
            gaps: components["schemas"]["TelemetryGap"][];
            nextPageToken?: string;
        };
        VehicleTelemetryHealth: {
            /** Format: uuid */
            vehicleId: string;
            status: components["schemas"]["GatewayHealthStatus"];
            /** Format: uuid */
            activeSessionId?: string;
            /** Format: date-time */
            lastSampleAt?: string;
            /** Format: int64 */
            lastSampleSequence?: number;
            /** Format: date-time */
            lastHeartbeatAt?: string;
            gatewayStatus?: components["schemas"]["GatewayHealthStatus"];
            openGapCount?: number;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state. Common codes: `IDEMPOTENCY_CONFLICT`, `TELEMETRY_SEQUENCE_CONFLICT`. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Batch too large (`TELEMETRY_BATCH_TOO_LARGE`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        GatewayIdPath: string;
        SessionIdPath: string;
        VehicleIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    telemetryIngestBatch: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryIngestBatch"];
            };
        };
        responses: {
            /** @description Batch accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryBatchAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    telemetryGatewayHeartbeat: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                gatewayId: components["parameters"]["GatewayIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayHeartbeat"];
            };
        };
        responses: {
            /** @description Heartbeat accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayHeartbeatAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    telemetrySessionTimeline: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                fromSequence?: number;
                toSequence?: number;
                includeSamples?: boolean;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry timeline. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryTimeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    telemetryVehicleHealth: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle telemetry health. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleTelemetryHealth"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
