/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/vehicle-edge-gateway/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["edgeHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe.
         * @description Reports whether the gateway can currently forward
         *     telemetry: serial input reachable AND upstream
         *     `vehicle-telemetry-service` reachable AND parser
         *     configured.
         */
        get: operations["edgeHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edge/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gateway runtime status.
         * @description Reports the gateway's view of its parser, serial port,
         *     pending forward queue depth, and last successful
         *     forward.
         */
        get: operations["edgeStatusGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edge/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a gateway heartbeat to the local edge process.
         * @description Used by the on-vehicle/RPi sidecar to signal that the
         *     hardware bus is still alive even when no telemetry
         *     samples were emitted. Distinct from
         *     `vehicle-telemetry-service` /telemetry/heartbeat: this
         *     endpoint stays inside the edge boundary and never
         *     forwards raw protocol fields.
         */
        post: operations["edgeHeartbeatPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edge/raw-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a single raw frame for parsing + forwarding.
         * @description Hardware-sidecar entry point: one unparsed frame payload
         *     (Lite-shape line, future binary formats behind the same
         *     contract) is parsed by the registered
         *     `ISerialFrameParser`, normalized into samples, and
         *     forwarded upstream. Closes the
         *     `RawSerialFrame → parser → forwarder` data flow.
         *     Reuses the `Idempotency-Key` header as the
         *     upstream batch id, so a replay short-circuits without
         *     re-forwarding.
         */
        post: operations["edgeRawFramePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edge/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a batch of parsed-by-edge sample frames.
         * @description Inbound API used by the local hardware sidecar to push
         *     ALREADY-PARSED samples for forwarding to
         *     `vehicle-telemetry-service`. The gateway re-validates
         *     and forwards. Raw serial / RS-232 / CAN bytes are NEVER
         *     accepted at this boundary — submitters parse the
         *     hardware layer locally and submit normalized
         *     `EdgeSample` shape.
         *
         *     Idempotency-Key required: re-submissions of the same
         *     batch (same `(gatewayId, batchId)`) return the original
         *     acceptance receipt without a second forward to the
         *     backend.
         */
        post: operations["edgeFramesPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            reason?: string;
        };
        EdgeReadinessDegraded: {
            /** @enum {string} */
            status: "degraded";
            /** @enum {string} */
            reason: "serial_input_unavailable" | "upstream_telemetry_unreachable" | "parser_not_configured" | "queue_overflow";
        };
        /**
         * @description Internal lifecycle state of the edge gateway process.
         *     `bootstrapping` = parser/serial bring-up not finished;
         *     `forwarding` = healthy forward path;
         *     `paused` = ops-side suspend;
         *     `failed` = unrecoverable state.
         * @enum {string}
         */
        GatewayPhase: "bootstrapping" | "forwarding" | "paused" | "failed";
        EdgeRuntimeStatus: {
            /** Format: uuid */
            gatewayId: string;
            phase: components["schemas"]["GatewayPhase"];
            /** Format: date-time */
            observedAt: string;
            /**
             * @description Identifies the loaded parser adapter. Raw protocol
             *     fields (port, baud, framing details) are NOT exposed.
             */
            parser: {
                name: string;
                version?: string;
            };
            queue: {
                pendingBatches: number;
                /** Format: date-time */
                lastForwardedAt?: string;
                /** Format: uuid */
                lastForwardedBatchId?: string;
            };
            upstream?: {
                reachable: boolean;
                /** Format: date-time */
                lastHeartbeatAt?: string;
            };
        };
        EdgeHeartbeat: {
            /** Format: uuid */
            gatewayId: string;
            /** Format: date-time */
            observedAt: string;
            phase?: components["schemas"]["GatewayPhase"];
            /** @description Optional operator-facing degradation note. */
            reason?: string;
        };
        EdgeHeartbeatAccepted: {
            /** Format: uuid */
            gatewayId: string;
            /** Format: date-time */
            acceptedAt: string;
            duplicate: boolean;
        };
        /**
         * @description Single unparsed frame submitted by the on-vehicle / RPi
         *     sidecar to the gateway's `/edge/raw-frame` endpoint.
         *     The `payload` is opaque text understood by the gateway's
         *     registered parser adapter (default Lite-shape line);
         *     actual raw bytes are decoded here and never re-emitted to
         *     a domain consumer.
         */
        EdgeRawFrameSubmission: {
            /** Format: uuid */
            vehicleId: string;
            /** @description Opaque parser-specific frame text. */
            payload: string;
            /** Format: date-time */
            receivedAt?: string;
            /** @enum {string} */
            coordinateFrame?: "legacyXY" | "normalizedXY" | "geodeticWgs84";
        };
        /**
         * @description Returned when the registered parser yields zero samples
         *     for the submitted payload (e.g. comment or blank line).
         *     Frame is acknowledged but not forwarded.
         */
        EdgeRawFrameNoop: {
            /** @enum {boolean} */
            accepted: true;
            samplesParsed: number;
            reason?: string;
        };
        /**
         * @description ONE parsed sample as submitted by the local hardware
         *     sidecar to the gateway. Shape mirrors
         *     `vehicle-telemetry-service.TelemetrySample` minus
         *     non-edge fields. Raw protocol fields (CAN id, raw
         *     bytes) are NOT carried.
         */
        EdgeSample: {
            /**
             * Format: int64
             * @description Per-batch local monotonic sequence.
             */
            sampleSequence: number;
            /** Format: date-time */
            occurredAt: string;
            position: {
                x: number;
                y: number;
            };
            speed?: number;
            heading?: number;
            /** @enum {string} */
            gear?: "park" | "reverse" | "neutral" | "drive";
            rpm?: number;
            /**
             * @description Normalized sensor flags (already mapped out of raw
             *     bitfields by the local parser). Same vocabulary as
             *     `vehicle-telemetry-service` SensorState.
             */
            sensors?: {
                [key: string]: boolean;
            };
        };
        EdgeFrameBatch: {
            /** Format: uuid */
            gatewayId: string;
            /** Format: uuid */
            batchId: string;
            /** Format: uuid */
            vehicleId: string;
            /** Format: uuid */
            examId?: string;
            /** @enum {string} */
            coordinateFrame?: "legacyXY" | "normalizedXY" | "geodeticWgs84";
            /** Format: date-time */
            observedAt?: string;
            samples: components["schemas"]["EdgeSample"][];
        };
        EdgeFrameBatchAccepted: {
            /** Format: uuid */
            gatewayId: string;
            /** Format: uuid */
            batchId: string;
            acceptedSampleCount: number;
            duplicate: boolean;
            /**
             * Format: uuid
             * @description UUID of the upstream
             *     `vehicle-telemetry-service.TelemetryIngestBatch`
             *     this edge batch was forwarded as.
             */
            forwardedTelemetryBatchId?: string;
        };
        ErrorBody: {
            code: string;
            message: string;
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
            /** @description Optional structured details. */
            details?: unknown;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description Validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Caller is not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Idempotency conflict or duplicate batch. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Sample envelope failed semantic validation. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unhandled gateway-side failure. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    edgeHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    edgeHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to forward. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Gateway degraded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeReadinessDegraded"];
                };
            };
        };
    };
    edgeStatusGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edge runtime status. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeRuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    edgeHeartbeatPost: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeHeartbeat"];
            };
        };
        responses: {
            /** @description Heartbeat accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeHeartbeatAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    edgeRawFramePost: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeRawFrameSubmission"];
            };
        };
        responses: {
            /** @description Frame accepted (either forwarded or no-op when parser yields zero samples). */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeFrameBatchAccepted"] | components["schemas"]["EdgeRawFrameNoop"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
            /** @description Upstream telemetry service is unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    edgeFramesPost: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeFrameBatch"];
            };
        };
        responses: {
            /** @description Batch accepted for forwarding. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeFrameBatchAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
