/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/vehicle-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vehicles with cursor pagination. */
        get: operations["vehiclesList"];
        put?: never;
        /** Register a new vehicle. */
        post: operations["vehicleRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        /** Get a vehicle by id. */
        get: operations["vehicleGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change vehicle status. */
        post: operations["vehicleChangeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/bind-gateway": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind an edge gateway to a vehicle.
         * @description Edge gateway is foreign-owned (vehicle-edge-gateway); only its `edgeGatewayId`
         *     (UUID) is passed here. Full edge gateway model is not embedded.
         */
        post: operations["vehicleBindGateway"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}/bind-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind a mobile/Android device to a vehicle.
         * @description Device is foreign-owned (android-device-management-service); only its
         *     `deviceId` (UUID) is passed here.
         */
        post: operations["vehicleBindDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description UPPER_SNAKE_CASE machine-readable code. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
            /** Format: uuid */
            vehicleId?: string;
        };
        /**
         * @description Reference to an edge gateway owned by `vehicle-edge-gateway`.
         *     Only id is exchanged; full model is not embedded.
         */
        EdgeGatewayRef: {
            /** Format: uuid */
            edgeGatewayId: string;
        };
        /**
         * @description Reference to a mobile/Android device owned by `android-device-management-service`.
         *     Only id is exchanged; full model is not embedded.
         */
        DeviceRef: {
            /** Format: uuid */
            deviceId: string;
        };
        /** @enum {string} */
        VehicleStatus: "registered" | "active" | "maintenance" | "decommissioned";
        /** @enum {string} */
        VehicleType: "passenger" | "truck" | "motorcycle" | "bus";
        VehicleRegistration: {
            plateNumber: string;
            type: components["schemas"]["VehicleType"];
            model: string;
            manufactureYear?: number;
            vin?: string;
        };
        Vehicle: {
            /** Format: uuid */
            vehicleId: string;
            plateNumber: string;
            type: components["schemas"]["VehicleType"];
            model: string;
            manufactureYear?: number;
            vin?: string;
            status: components["schemas"]["VehicleStatus"];
            /** Format: date-time */
            statusChangedAt?: string;
            statusChangedBy?: components["schemas"]["ActorContext"];
            boundEdgeGateway?: components["schemas"]["EdgeGatewayRef"];
            boundDevice?: components["schemas"]["DeviceRef"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        VehicleStatusChange: {
            targetStatus: components["schemas"]["VehicleStatus"];
            reason: string;
        };
        EdgeGatewayBinding: {
            edgeGatewayRef: components["schemas"]["EdgeGatewayRef"];
        };
        DeviceBinding: {
            deviceRef: components["schemas"]["DeviceRef"];
        };
        VehiclesPage: {
            items: components["schemas"]["Vehicle"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including IDEMPOTENCY_CONFLICT. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
        SortBy: "createdAt" | "plateNumber";
        SortOrder: "asc" | "desc";
        VehicleIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    vehiclesList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortBy?: components["parameters"]["SortBy"];
                sortOrder?: components["parameters"]["SortOrder"];
                status?: components["schemas"]["VehicleStatus"];
                edgeGatewayId?: string;
                createdAtFrom?: string;
                createdAtTo?: string;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicles page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclesPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    vehicleRegister: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRegistration"];
            };
        };
        responses: {
            /** @description Vehicle registered. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    vehicleGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    vehicleChangeStatus: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleStatusChange"];
            };
        };
        responses: {
            /** @description Vehicle after status change. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    vehicleBindGateway: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeGatewayBinding"];
            };
        };
        responses: {
            /** @description Vehicle after binding. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    vehicleBindDevice: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                vehicleId: components["parameters"]["VehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceBinding"];
            };
        };
        responses: {
            /** @description Vehicle after binding. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
