/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/violation-rule-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List violations with cursor pagination. */
        get: operations["violationsList"];
        put?: never;
        /** Create a violation catalog entry. */
        post: operations["violationCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/violations/{violationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                violationId: components["parameters"]["ViolationIdPath"];
            };
            cookie?: never;
        };
        /** Get a violation by id. */
        get: operations["violationGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rule definitions. */
        get: operations["rulesList"];
        put?: never;
        /**
         * Create a rule definition (draft).
         * @description Creates a new draft rule definition bound to a violation. The
         *     first call may include a `conditionTree`; otherwise the rule
         *     is created empty and the body must be completed before
         *     publication.
         */
        post: operations["ruleCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: components["parameters"]["RuleIdPath"];
            };
            cookie?: never;
        };
        /**
         * Get a rule definition.
         * @description Returns the latest published version by default. Pass
         *     `ruleVersion` to fetch a specific historical version
         *     (reproducible evaluation).
         */
        get: operations["ruleGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{ruleId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: components["parameters"]["RuleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a new immutable version of a rule.
         * @description Promotes the current draft to a published `ruleVersion`.
         *     Previous published versions remain addressable for
         *     reproducible evaluation of historical exam results.
         */
        post: operations["rulePublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate a rule against context.
         * @description Synchronous evaluation of one or more rules for a given exam
         *     context. Body carries refs to exam/exercise context and the
         *     triggering event payload. Caller may pin `ruleVersion` for
         *     reproducibility; otherwise the latest published version is
         *     used.
         *
         *     Evaluations are not idempotent in the create/replace sense
         *     (same inputs may yield the same detection many times if the
         *     caller chooses), but for caller-initiated dedup the
         *     `Idempotency-Key` header may be supplied; servers MAY treat
         *     it as a replay key.
         */
        post: operations["ruleEvaluate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{examId}/violation-facts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        /** List persisted violation facts for an exam. */
        get: operations["examViolationFacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description UPPER_SNAKE_CASE machine-readable code. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        /** @enum {string} */
        Severity: "low" | "medium" | "high" | "critical";
        /** @enum {string} */
        RuleStatus: "draft" | "published" | "archived";
        ExamRef: {
            /** Format: uuid */
            examId: string;
        };
        /**
         * @description Reference to an exercise version owned by `exercise-service`.
         *     `exerciseVersionId` is required so the evaluation is
         *     reproducible after a re-publish.
         */
        ExerciseRef: {
            /** Format: uuid */
            exerciseId: string;
            /** Format: uuid */
            exerciseVersionId: string;
        };
        ViolationRef: {
            /** Format: uuid */
            violationId: string;
        };
        /**
         * @description Pointer to evidence backing a detected violation. The exact
         *     kind (`telemetrySample`, `audioSegment`, `videoFrame`,
         *     `biometryCheck`, `geometryHit`) lives in the producing
         *     service; only id-level refs cross service boundaries here.
         */
        EvidenceRef: {
            /** @enum {string} */
            kind: "telemetrySample" | "audioSegment" | "videoFrame" | "biometryCheck" | "geometryHit";
            /** Format: uuid */
            id: string;
        };
        /**
         * @description Opaque AST describing rule preconditions over telemetry,
         *     audio, biometry and geometry contexts. Authored by the rule
         *     editor; canonical structure is fixed by the editor's domain
         *     model. For the OpenAPI baseline only the wrapper is
         *     described; per-node schema may be added later.
         */
        ConditionTree: {
            [key: string]: unknown;
        };
        ViolationCreation: {
            code: string;
            title: string;
            description?: string;
            severity: components["schemas"]["Severity"];
        };
        Violation: {
            /** Format: uuid */
            violationId: string;
            code: string;
            title: string;
            description?: string;
            severity: components["schemas"]["Severity"];
            /** @description Currently published rule version bound to this violation, if any. */
            activeRuleVersion?: {
                /** Format: uuid */
                ruleId: string;
                ruleVersion: number;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ViolationsPage: {
            items: components["schemas"]["Violation"][];
            nextPageToken?: string;
        };
        /** @description Body of `POST /rules` — creates a draft rule. */
        RuleDraft: {
            violationRef: components["schemas"]["ViolationRef"];
            title: string;
            description?: string;
            /**
             * @description Logical input descriptors (e.g. telemetry signal kinds,
             *     audio trigger kinds, biometry check kinds) consumed by
             *     the condition tree. Free-form on baseline; tightened by
             *     rule editor schema later.
             */
            inputs?: {
                [key: string]: unknown;
            }[];
            conditionTree?: components["schemas"]["ConditionTree"];
            /**
             * @description Declarative actions to take when conditions match. Baseline
             *     keeps the shape generic; the rule editor narrows it.
             */
            actions?: {
                [key: string]: unknown;
            }[];
        };
        RulePublishRequest: {
            conditionTree: components["schemas"]["ConditionTree"];
            inputs?: {
                [key: string]: unknown;
            }[];
            actions?: {
                [key: string]: unknown;
            }[];
            notes?: string;
        };
        RuleDefinition: {
            /** Format: uuid */
            ruleId: string;
            violationRef: components["schemas"]["ViolationRef"];
            title?: string;
            description?: string;
            ruleVersion: number;
            status: components["schemas"]["RuleStatus"];
            inputs?: {
                [key: string]: unknown;
            }[];
            conditionTree?: components["schemas"]["ConditionTree"];
            actions?: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            publishedAt?: string;
            publishedBy?: components["schemas"]["ActorContext"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RulesPage: {
            items: components["schemas"]["RuleDefinition"][];
            nextPageToken?: string;
        };
        RuleEvaluationRequest: {
            examRef: components["schemas"]["ExamRef"];
            exerciseRef?: components["schemas"]["ExerciseRef"];
            /**
             * @description Refs to surrounding context (telemetry, audio, biometry,
             *     geometry) the evaluator may pull on demand. Opaque for
             *     the baseline.
             */
            contextRefs: {
                [key: string]: unknown;
            }[];
            /** @description Triggering event payload, opaque on the baseline. */
            eventPayload: {
                [key: string]: unknown;
            };
            /**
             * @description Pin a specific rule version for reproducibility. When
             *     omitted, the latest published version applies.
             */
            ruleVersion?: number;
            /**
             * @description Optional list of ruleIds to consider; when omitted, all
             *     published rules bound to the exam's exercise apply.
             */
            rulesScope?: string[];
        };
        RuleEvaluationResponse: {
            /** Format: uuid */
            evaluationId: string;
            /** Format: date-time */
            evaluatedAt: string;
            detectedViolations: components["schemas"]["ViolationDetected"][];
        };
        /**
         * @description Synchronous mirror of `autodrome.violation.detected.v1` (see
         *     `contracts/events/violation/detected.v1.schema.json`). The
         *     same shape is published over the bus by violation-rule-service
         *     when running in async mode.
         */
        ViolationDetected: {
            /** Format: uuid */
            detectionId: string;
            examRef: components["schemas"]["ExamRef"];
            violationRef: components["schemas"]["ViolationRef"];
            /** Format: uuid */
            ruleId?: string;
            ruleVersion: number;
            /** Format: date-time */
            occurredAt: string;
            severity: components["schemas"]["Severity"];
            evidenceRefs?: components["schemas"]["EvidenceRef"][];
        };
        ViolationFactView: {
            /** Format: uuid */
            factId: string;
            examRef: components["schemas"]["ExamRef"];
            violationRef: components["schemas"]["ViolationRef"];
            violationCode: string;
            /** Format: uuid */
            ruleId?: string;
            ruleVersion: number;
            severity: components["schemas"]["Severity"];
            /** Format: uuid */
            telemetrySessionId?: string;
            /** Format: int64 */
            sampleSequence?: number;
            /** Format: date-time */
            occurredAt: string;
        };
        ExamViolationFactsPage: {
            items: components["schemas"]["ViolationFactView"][];
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
            /** Format: uuid */
            vehicleId?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflicting state, including IDEMPOTENCY_CONFLICT. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
        SortOrder: "asc" | "desc";
        ViolationIdPath: string;
        RuleIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    violationsList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortOrder?: components["parameters"]["SortOrder"];
                severity?: components["schemas"]["Severity"];
                code?: string;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Violations page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViolationsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    violationCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViolationCreation"];
            };
        };
        responses: {
            /** @description Violation created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    violationGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                violationId: components["parameters"]["ViolationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Violation. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    rulesList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                violationId?: string;
                status?: components["schemas"]["RuleStatus"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ruleCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleDraft"];
            };
        };
        responses: {
            /** @description Rule created (draft). */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ruleGet: {
        parameters: {
            query?: {
                ruleVersion?: number;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                ruleId: components["parameters"]["RuleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule definition. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    rulePublish: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                ruleId: components["parameters"]["RuleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePublishRequest"];
            };
        };
        responses: {
            /** @description Rule definition after publish. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ruleEvaluate: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleEvaluationRequest"];
            };
        };
        responses: {
            /** @description Evaluation outcome. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleEvaluationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    examViolationFacts: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Violation facts for the exam. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamViolationFactsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
