/* AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by `pnpm contracts:generate` from
 *   contracts/openapi/virtual-vehicle-service/v1/openapi.yaml
 * via openapi-typescript. Edit the canonical OpenAPI spec in the
 * backend monorepo instead and re-run `pnpm contracts:generate`.
 */

export interface paths {
    "/virtual-vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List virtual vehicles with cursor pagination. */
        get: operations["virtualVehiclesList"];
        put?: never;
        /**
         * Register a new virtual vehicle.
         * @description Creates a virtual vehicle in `draft` status. The caller chooses
         *     `simulatorSource` (`webVirtual` for Web emulator,
         *     `rpiHardware` for a remote RPi acting through this domain
         *     plane, `importedLegacy` for vehicles materialized from a
         *     legacy file). A `currentScenarioId` may be supplied at
         *     creation; otherwise it is attached later via PATCH.
         */
        post: operations["virtualVehicleCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        /** Get a virtual vehicle by id. */
        get: operations["virtualVehicleGet"];
        put?: never;
        post?: never;
        /**
         * Delete a virtual vehicle.
         * @description Delete is only allowed from `draft` / `stopped` / `failed`
         *     statuses. A `running` or `paused` vehicle must be stopped
         *     first; the server refuses with `409` otherwise.
         */
        delete: operations["virtualVehicleDelete"];
        options?: never;
        head?: never;
        /**
         * Partially update a virtual vehicle.
         * @description Patch allows changing `displayName`, attaching or replacing
         *     `currentScenarioId`, and updating the `telemetryProfile`.
         *     Status transitions and exam assignment must use their
         *     dedicated endpoints — patch refuses to overwrite them.
         */
        patch: operations["virtualVehiclePatch"];
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List simulator scenarios with cursor pagination. */
        get: operations["scenariosList"];
        put?: never;
        /**
         * Register a new simulator scenario.
         * @description Stores a scenario document compatible with both Web and
         *     legacy/RPi adapters. The `source` discriminates how the
         *     scenario was authored (`web` = composed in Web UI;
         *     `legacyLiteReplay` = imported from a legacy Lite
         *     tab-separated replay file; `legacyFullTrajectory` = imported
         *     from a full emulator trajectory) and decides which optional
         *     sub-document the engine consumes (`motionProfile` for
         *     generated, `replayProfile` for legacy imports).
         *
         *     `yawProfile` is required: it captures whether the recorded
         *     yaw is direct (`liteDirectYaw`), needs the legacy
         *     VehicleState transform (`fullVehicleStateYaw`), comes from a
         *     GSOF over TCP capture (`tcpGsofYaw`), or is already in the
         *     normalized backend frame (`normalized`). This is a
         *     production boundary requirement, not a migration detail.
         */
        post: operations["scenarioCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["ScenarioIdPath"];
            };
            cookie?: never;
        };
        /** Get a scenario by id. */
        get: operations["scenarioGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/assign-exam": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a virtual vehicle to an exam context.
         * @description The exam itself lives in `exam-service`; this endpoint
         *     only stores the `assignedExamId` reference. Re-assigning an
         *     already-assigned virtual vehicle to a different exam is
         *     rejected with `409`; clearing the assignment is a separate
         *     future operation.
         */
        post: operations["virtualVehicleAssignExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a session for the virtual vehicle.
         * @description Allowed from `draft` or `ready` status with a non-null
         *     `currentScenarioId`. Starts the session, transitions to
         *     `running` and returns the resulting
         *     `VirtualVehicleSession`. Retrying with the same
         *     `Idempotency-Key` replays the previous session reference
         *     byte-equivalently; reusing the key with a different body
         *     returns `409 IDEMPOTENCY_CONFLICT`.
         */
        post: operations["virtualVehicleStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause the running session.
         * @description Allowed only from `running` status. The session is moved to
         *     `paused` and the engine stops emitting telemetry samples
         *     until resumed.
         */
        post: operations["virtualVehiclePause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused session.
         * @description Allowed only from `paused` status; returns the session in
         *     `running` status.
         */
        post: operations["virtualVehicleResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop the active session.
         * @description Allowed from `running` or `paused`. The vehicle transitions
         *     to `stopped`; the previously active session is closed and
         *     its `stoppedAt` is populated.
         */
        post: operations["virtualVehicleStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/reset-position": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset the virtual vehicle's position to scenario start.
         * @description Allowed from `ready`, `stopped`, `paused` or `failed`. The
         *     vehicle's `currentPosition`, `yaw`, `speed` and `gear` are
         *     reset to the values declared on `currentScenarioId`.
         *     Refused with `409` while a session is `running`.
         */
        post: operations["virtualVehicleResetPosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/manual-control": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a manual control command to the running session.
         * @description Operator-issued control input. Used when the active
         *     scenario `type` is `manual` (driver-in-the-loop) and on
         *     `generated` / `replay` scenarios as overrides (e.g.
         *     emergency stop). The command embeds normalized actuator
         *     values; raw UDP/TCP/serial payloads are NEVER accepted at
         *     this boundary.
         */
        post: operations["virtualVehicleManualControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtual-vehicles/{virtualVehicleId}/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        /**
         * List events recorded for a session.
         * @description Returns the chronologically-ordered event timeline of a
         *     single session — lifecycle transitions, manual control
         *     commands, replay milestones, sensor flips, errors. Backed by
         *     cursor pagination.
         */
        get: operations["virtualVehicleSessionEventsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description UPPER_SNAKE_CASE machine-readable code. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        ActorContext: {
            /** @enum {string} */
            actorType: "user" | "service" | "device" | "system";
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId?: string;
            /** Format: uuid */
            stationId?: string;
            /** Format: uuid */
            vehicleId?: string;
        };
        /**
         * @description Reference to a physical vehicle owned by `vehicle-service`.
         *     Only id is exchanged; full vehicle master-data lives there.
         */
        VehicleRef: {
            /** Format: uuid */
            vehicleId: string;
        };
        /**
         * @description Reference to an exam owned by `exam-service`. Only id is
         *     exchanged; exam lifecycle remains in its owning service.
         */
        ExamRef: {
            /** Format: uuid */
            examId: string;
        };
        /**
         * @description Lifecycle of a virtual vehicle:
         *     - `draft` — created, no scenario or not yet ready;
         *     - `ready` — scenario attached and idle, ready to start;
         *     - `running` — session is emitting telemetry samples;
         *     - `paused` — session suspended, no samples emitted;
         *     - `stopped` — session closed gracefully;
         *     - `failed` — session terminated by error and requires reset.
         * @enum {string}
         */
        VirtualVehicleStatus: "draft" | "ready" | "running" | "paused" | "stopped" | "failed";
        /**
         * @description Origin of the simulator implementation:
         *     - `webVirtual` — Web emulator running inside the local node;
         *     - `rpiHardware` — remote RPi acting through this domain
         *       plane (kept here for fleet uniformity, not for raw
         *       protocol carry-through);
         *     - `importedLegacy` — vehicle materialized from a legacy file.
         * @enum {string}
         */
        SimulatorSource: "webVirtual" | "rpiHardware" | "importedLegacy";
        /**
         * @description Scenario authoring shape:
         *     - `generated` — algorithmic motion using legacy constants
         *       (`frontWheel=(-1,0)`, `rearWheel=(-3,0)`, `axleBase=2`,
         *       `maxAngle=0.6`) plus normalized yaw;
         *     - `replay` — replay of a previously recorded trajectory;
         *     - `manual` — driver-in-the-loop, no scripted motion;
         *     - `scripted` — composite event-driven script (geometry +
         *       control events).
         * @enum {string}
         */
        ScenarioType: "generated" | "replay" | "manual" | "scripted";
        /**
         * @description How the scenario document arrived at the service:
         *     - `web` — authored in the Web UI;
         *     - `legacyLiteReplay` — imported from a legacy Lite
         *       tab-separated replay file (raw `sensors` mask, direct
         *       yaw);
         *     - `legacyFullTrajectory` — imported from a legacy full
         *       emulator trajectory (`VehicleStateFlags`, transformed
         *       yaw).
         * @enum {string}
         */
        ScenarioSource: "web" | "legacyLiteReplay" | "legacyFullTrajectory";
        /**
         * @description Compatibility envelope the scenario satisfies:
         *     - `webOnly` — Web emulator only;
         *     - `webAndRpi` — both Web emulator and RPi adapter;
         *     - `rpiLegacy` — legacy RPi pipeline only (used during
         *       import; should be transformed to `webAndRpi` once the
         *       scenario is normalized).
         * @enum {string}
         */
        ScenarioCompatibilityProfile: "webOnly" | "webAndRpi" | "rpiLegacy";
        /**
         * @description Coordinate frame in which `currentPosition` and motion
         *     samples are expressed:
         *     - `legacyXY` — legacy emulator XY (meters);
         *     - `normalizedXY` — backend-normalized XY (meters);
         *     - `geodeticWgs84` — WGS84 lat/lon (degrees); used for
         *       full-trajectory imports recorded by GSOF capture.
         * @enum {string}
         */
        CoordinateFrame: "legacyXY" | "normalizedXY" | "geodeticWgs84";
        /**
         * @description Yaw representation kept with the scenario so the adapter
         *     can apply the correct transform:
         *     - `liteDirectYaw` — Lite emulator local packet writes
         *       `CurYaw` directly;
         *     - `fullVehicleStateYaw` — full emulator stores
         *       `VehicleState.Yaw = -angle + PI/2`;
         *     - `tcpGsofYaw` — full TCP/GSOF capture stores
         *       `0.5*PI - angle`;
         *     - `normalized` — backend-normalized canonical yaw.
         * @enum {string}
         */
        YawProfile: "liteDirectYaw" | "fullVehicleStateYaw" | "tcpGsofYaw" | "normalized";
        /** @enum {string} */
        GearSelection: "reverse" | "neutral" | "drive";
        /**
         * @description Domain-level event categories recorded on the session
         *     timeline. Raw transport packets are NOT recorded — every
         *     event already speaks normalized vocabulary.
         * @enum {string}
         */
        SessionEventType: "sessionStarted" | "sessionPaused" | "sessionResumed" | "sessionStopped" | "sessionFailed" | "manualControlApplied" | "replayMilestoneReached" | "sensorStateChanged" | "resetPosition" | "telemetrySampleEmitted" | "scenarioImportFailed";
        Position2D: {
            x: number;
            y: number;
        };
        /**
         * @description Normalized sensor flags. Boolean fields only; legacy bit
         *     masks and `VehicleStateFlags` are mapped to these on
         *     import.
         */
        SensorState: {
            engineOn?: boolean;
            ignitionOn?: boolean;
            leftIndicator?: boolean;
            rightIndicator?: boolean;
            hazardLights?: boolean;
            headlightsLow?: boolean;
            headlightsHigh?: boolean;
            wipers?: boolean;
            horn?: boolean;
            seatbelt?: boolean;
            handbrake?: boolean;
            doorsClosed?: boolean;
            clutchPressed?: boolean;
            brakePressed?: boolean;
        };
        /**
         * @description Cadence and channel selection for normalized telemetry
         *     samples this virtual vehicle will publish through
         *     `vehicle-telemetry-service`. Transport-level details
         *     (broker subjects, ports) are NOT part of this object.
         */
        TelemetryProfile: {
            /** @description Target interval between samples in milliseconds. */
            sampleIntervalMs: number;
            channels: ("position" | "velocity" | "acceleration" | "yaw" | "gear" | "sensorState" | "rpm" | "fuel")[];
        };
        /**
         * @description Generated-motion parameters used by `generated` scenarios.
         *     Constants kept legacy-compatible per architecture doc.
         */
        MotionProfile: {
            /** @description Max speed in m/s. */
            maxSpeed: number;
            /** @description Max steering angle in radians; legacy baseline 0.6 rad. */
            maxSteeringAngle: number;
            /** @description Wheelbase in meters; legacy baseline 2.0 m. */
            axleBase?: number;
            frontWheelOffset?: components["schemas"]["Position2D"];
            rearWheelOffset?: components["schemas"]["Position2D"];
        };
        /**
         * @description Replay metadata describing how the recorded trajectory was
         *     captured. Used by `legacyLiteReplay` and
         *     `legacyFullTrajectory` scenarios. Does NOT carry raw
         *     transport packets.
         */
        ReplayProfile: {
            sampleCount: number;
            durationMs: number;
            /** @description Loop the trajectory when reaching the end. */
            repeat?: boolean;
            /**
             * @description Original Lite-import sensor mask bit width. Kept for
             *     audit only — runtime engine consumes the normalized
             *     `SensorState` boolean fields.
             */
            liteSensorMaskBits?: number;
            /**
             * @description Original full-trajectory VehicleStateFlags bit width.
             *     Audit-only; runtime consumes normalized fields.
             */
            fullVehicleStateFlagsBits?: number;
        };
        SimulatorScenarioInitialState: {
            position: components["schemas"]["Position2D"];
            yaw: number;
            speed?: number;
            gear?: components["schemas"]["GearSelection"];
            sensorState?: components["schemas"]["SensorState"];
        };
        SimulatorScenarioCreate: {
            name: string;
            type: components["schemas"]["ScenarioType"];
            source: components["schemas"]["ScenarioSource"];
            compatibilityProfile: components["schemas"]["ScenarioCompatibilityProfile"];
            coordinateFrame: components["schemas"]["CoordinateFrame"];
            yawProfile: components["schemas"]["YawProfile"];
            initialState: components["schemas"]["SimulatorScenarioInitialState"];
            motionProfile?: components["schemas"]["MotionProfile"];
            replayProfile?: components["schemas"]["ReplayProfile"];
        };
        SimulatorScenario: {
            /** Format: uuid */
            scenarioId: string;
            name: string;
            type: components["schemas"]["ScenarioType"];
            source: components["schemas"]["ScenarioSource"];
            compatibilityProfile: components["schemas"]["ScenarioCompatibilityProfile"];
            coordinateFrame: components["schemas"]["CoordinateFrame"];
            yawProfile: components["schemas"]["YawProfile"];
            initialState: components["schemas"]["SimulatorScenarioInitialState"];
            motionProfile?: components["schemas"]["MotionProfile"];
            replayProfile?: components["schemas"]["ReplayProfile"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SimulatorScenariosPage: {
            items: components["schemas"]["SimulatorScenario"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
        VirtualVehicleCreate: {
            displayName: string;
            simulatorSource: components["schemas"]["SimulatorSource"];
            compatibilityProfile: components["schemas"]["ScenarioCompatibilityProfile"];
            /** Format: uuid */
            currentScenarioId?: string;
            vehicleRef?: components["schemas"]["VehicleRef"];
            telemetryProfile?: components["schemas"]["TelemetryProfile"];
        };
        /**
         * @description Patch supports a small set of mutable fields. Status
         *     transitions and exam assignment have their own endpoints.
         */
        VirtualVehiclePatch: {
            displayName?: string;
            /** Format: uuid */
            currentScenarioId?: string;
            telemetryProfile?: components["schemas"]["TelemetryProfile"];
        };
        VirtualVehicle: {
            /** Format: uuid */
            virtualVehicleId: string;
            displayName: string;
            status: components["schemas"]["VirtualVehicleStatus"];
            simulatorSource: components["schemas"]["SimulatorSource"];
            compatibilityProfile: components["schemas"]["ScenarioCompatibilityProfile"];
            /** Format: uuid */
            currentScenarioId?: string;
            vehicleRef?: components["schemas"]["VehicleRef"];
            assignedExam?: components["schemas"]["ExamRef"];
            /** Format: uuid */
            currentSessionId?: string;
            currentPosition?: components["schemas"]["Position2D"];
            yaw?: number;
            speed?: number;
            gear?: components["schemas"]["GearSelection"];
            sensorState?: components["schemas"]["SensorState"];
            telemetryProfile?: components["schemas"]["TelemetryProfile"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        VirtualVehiclesPage: {
            items: components["schemas"]["VirtualVehicle"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
        AssignExamRequest: {
            examRef: components["schemas"]["ExamRef"];
        };
        /**
         * @description Optional override fields applied on top of the virtual
         *     vehicle's current configuration when starting a session.
         *     Omitting the body starts with the existing
         *     `currentScenarioId` and `telemetryProfile`.
         */
        SessionStartRequest: {
            /** Format: uuid */
            scenarioId?: string;
            telemetryProfile?: components["schemas"]["TelemetryProfile"];
        };
        SessionStopRequest: {
            /** @description Operator audit note for the stop transition. */
            reason?: string;
        };
        VirtualVehicleSession: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            virtualVehicleId: string;
            /** Format: uuid */
            scenarioId: string;
            status: components["schemas"]["VirtualVehicleStatus"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            stoppedAt?: string;
            assignedExam?: components["schemas"]["ExamRef"];
            emittedSamplesCount?: number;
            /** Format: date-time */
            lastSampleAt?: string;
        };
        /**
         * @description Normalized operator input. All actuator values are
         *     bounded to `[-1, 1]` (steering) or `[0, 1]` (throttle/brake);
         *     the engine refuses out-of-range values with `422`. The
         *     command does NOT carry raw transport packets — those stay
         *     in `vehicle-edge-gateway` / `vehicle-simulator-rpi`.
         */
        ManualControlCommand: {
            /** Format: date-time */
            issuedAt: string;
            throttle?: number;
            brake?: number;
            /** @description Normalized steering angle, -1 = full left, +1 = full right. */
            steering?: number;
            gear?: components["schemas"]["GearSelection"];
            sensorState?: components["schemas"]["SensorState"];
            notes?: string;
        };
        ManualControlAccepted: {
            /** Format: uuid */
            virtualVehicleId: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: date-time */
            acceptedAt: string;
        };
        SessionEvent: {
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            sessionId: string;
            type: components["schemas"]["SessionEventType"];
            /** Format: date-time */
            occurredAt: string;
            actor?: components["schemas"]["ActorContext"];
            /**
             * @description Event-specific normalized fields. Stays domain-level;
             *     no raw transport payloads land here.
             */
            details?: {
                [key: string]: unknown;
            };
        };
        SessionEventsPage: {
            items: components["schemas"]["SessionEvent"][];
            /** @description Empty/absent when no further pages. */
            nextPageToken?: string;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Conflicting state. Common codes: `IDEMPOTENCY_CONFLICT`,
         *     `VIRTUAL_VEHICLE_INVALID_TRANSITION`,
         *     `VIRTUAL_VEHICLE_ALREADY_ASSIGNED`,
         *     `SCENARIO_INCOMPATIBLE`.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        IdempotencyKey: string;
        PageSize: number;
        PageToken: string;
        SortOrder: "asc" | "desc";
        VirtualVehicleIdPath: string;
        ScenarioIdPath: string;
        SessionIdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id used in this response. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    virtualVehiclesList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortOrder?: components["parameters"]["SortOrder"];
                status?: components["schemas"]["VirtualVehicleStatus"];
                simulatorSource?: components["schemas"]["SimulatorSource"];
                assignedExamId?: string;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual vehicles page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehiclesPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VirtualVehicleCreate"];
            };
        };
        responses: {
            /** @description Virtual vehicle created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual vehicle. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleDelete: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual vehicle deleted. */
            204: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehiclePatch: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VirtualVehiclePatch"];
            };
        };
        responses: {
            /** @description Virtual vehicle after patch. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    scenariosList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                sortOrder?: components["parameters"]["SortOrder"];
                type?: components["schemas"]["ScenarioType"];
                source?: components["schemas"]["ScenarioSource"];
                compatibilityProfile?: components["schemas"]["ScenarioCompatibilityProfile"];
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenarios page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorScenariosPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    scenarioCreate: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulatorScenarioCreate"];
            };
        };
        responses: {
            /** @description Scenario created. */
            201: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorScenario"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    scenarioGet: {
        parameters: {
            query?: never;
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                scenarioId: components["parameters"]["ScenarioIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorScenario"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleAssignExam: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignExamRequest"];
            };
        };
        responses: {
            /** @description Virtual vehicle after exam assignment. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleStart: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionStartRequest"];
            };
        };
        responses: {
            /** @description Session started. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicleSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehiclePause: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session paused. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicleSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleResume: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session resumed. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicleSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleStop: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionStopRequest"];
            };
        };
        responses: {
            /** @description Virtual vehicle after stop. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleResetPosition: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual vehicle after reset. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualVehicle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleManualControl: {
        parameters: {
            query?: never;
            header: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualControlCommand"];
            };
        };
        responses: {
            /** @description Command accepted. */
            202: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualControlAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    virtualVehicleSessionEventsList: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                pageToken?: components["parameters"]["PageToken"];
                type?: components["schemas"]["SessionEventType"];
                fromTimestamp?: string;
                toTimestamp?: string;
            };
            header?: {
                "Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                virtualVehicleId: components["parameters"]["VirtualVehicleIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session events page. */
            200: {
                headers: {
                    "Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEventsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
